<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Schema;
use Artisan;
use App\Models\Config;
use App\Pivlu\Setup;


class UpdateCommand extends Command
{


    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'pivlu:update';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Allows to update the app directly through CLI';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {

        if (!Schema::hasTable('pivlu_config')) {
            $this->error('Pivlu is not installed!');
            $this->line('You can install Pivlu using "pivlu:install" command.');
            return;
        }

        if (!Config::get_config('installed_at')) {
            $this->error('Pivlu is not installed!');
            $this->line('You can install Pivlu using "pivlu:install" command.');
            return;
        }

        $this->line('Update database tables');
        Artisan::call('migrate');

        $this->line('Check default language');
        Setup::check_default_language();

        $this->line('Check website settings');
        Setup::check_default_website_settings();

        $this->line('Check default post types');
        Setup::check_default_post_types();

        $this->line('Check default block types');
        Setup::check_default_block_types();

        // Create the symbolic link 
        Artisan::call('storage:link');

        Config::update_config('updated_at', now());
        $this->info('The update was successful!');
    }
}
