<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

use Pivlu\Models\Theme;
use Pivlu\Models\Language;
use Pivlu\Models\Config;
use Pivlu\Models\Block;
use Pivlu\Models\BlockContent;
use Pivlu\Models\ThemeFooterBlock;


// Get blocks for homepage
if (!function_exists('homepage_blocks')) {
	function homepage_blocks()
	{
		$active_theme = Theme::get_active_theme();
		if (! $active_theme) return [];

		$blocks = Block::where(['theme_id' => $active_theme->id, 'is_homepage_block' => 1, 'hidden' => 0])->orderBy('position')->get();
		return $blocks ?? [];
	}
}


// show content block 
if (!function_exists('block')) {
	function block($id)
	{

		$data = ['content' => null];
		$block = Block::find($id);
		if (!$block) return (object)$data;
		if ($block->hidden == 1) return (object)$data;

		$block_content = BlockContent::where('block_id', $id)->where('lang_id', Language::get_active_language()->id ?? null)->first();

		$data = array('content' => $block_content->content ?? null, 'header' => $block_content->header ?? null);

		return (object)$data;
	}
}


if (!function_exists('get_block_content_item')) {
	function get_block_content_item($block_id, $lang_id, $code)
	{
		$content = BlockContent::where('block_id', $block_id)->where('lang_id', $lang_id)->value('content');
		$items = json_decode($content);
		if (! $items) return null;
		if (! $code) return null;

		foreach ($items as $item) {
			if ($item->code == $code) return $item;
		}

		return;
	}
}


// Get blocks for a specific footer column
if (!function_exists('footer_blocks')) {
	function footer_blocks($footer_id, $destination, $col)
	{
		// get footer layout (number of columns)
		if ($destination == 'primary') $layout = Config::get_config('tpl_footer_columns') ?? 1;
		if ($destination == 'secondary') $layout = Config::get_config('tpl_footer2_columns') ?? 1;

		$blocks = ThemeFooterBlock::with('block_type')->where(['footer_id' => $footer_id, 'destination' => $destination, 'col' => $col])->where('hidden', 0)->orderBy('position')->get();

		return $blocks ?? [];
	}
}


// show footer block 
if (!function_exists('footer_block')) {
	function footer_block($id)
	{

		$data = ['content' => null];
		$block = ThemeFooterBlock::find($id);
		if (!$block) return (object)$data;
		if ($block->hidden == 1) return (object)$data;

		$block_content = ThemeFooterBlockContent::where('footer_block_id', $id)->where('lang_id', Language::get_active_language()->id ?? null)->first();

		$data = array('content' => $block_content->content ?? null, 'header' => $block_content->header ?? null, 'settings' => json_decode($block->settings) ?? null);

		return (object)$data;
	}
}


// Get blocks for a specific layout column
if (!function_exists('layout_blocks')) {
	function layout_blocks($id, $section, $show_hidden = null)
	{
		$blocks = ThemeLayoutBlock::where('layout_id', $id)->where('section', $section);

		if (!$show_hidden) $blocks = $blocks->where('hide', 0);

		$blocks = $blocks->orderBy('position')->get();
		if (!$blocks) return array();

		return $blocks;
	}
}


// show layout block 
if (!function_exists('layout_block')) {
	function layout_block($id)
	{
		$data = array('settings' => null, 'content' => null, 'header' => null);

		$block = ThemeLayoutBlock::find($id);

		if (!$block) return (object)$data;

		$block_content = ThemeLayoutBlockContent::where('block_id', $id)->where('lang_id', Language::get_active_language()->id)->first();

		$data = array('content' => $block_content->content ?? null, 'header' => $block_content->header ?? null, 'settings' => (object)unserialize($block->settings));

		return (object)$data;
	}
}
