<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

use Pivlu\Models\Language;

if (!function_exists('get_default_language')) {
	function get_default_language()
	{
		$lang = Language::where('is_default', 1)->first();

		return $lang;
	}
}

if (!function_exists('get_active_language')) {
	function get_active_language()
	{
		$lang = Language::get_active_language();

		return $lang;
	}
}

if (!function_exists('get_language_code_from_id')) {
	function get_language_code_from_id($id)
	{

		$code = Language::where('id', $id)->value('code');

		return $code;
	}
}

// Get only 'active' languages
if (!function_exists('languages')) {
	function languages()
	{
		$items = Language::where('status', 'active')->orderByDesc('is_default')->orderBy('name')->get();

		return $items;
	}
}

// Get 'active' and 'inactive' languages
if (!function_exists('admin_languages')) {
	function admin_languages()
	{
		$items = Language::where('status', '!=', 'disabled')->orderByDesc('is_default')->orderBy('name')->get();

		return $items;
	}
}


if (!function_exists('lang_label')) {
	function lang_label($text, $lang)
	{
		if (count(admin_languages()) > 1) {
			$data = flag($lang->code) . ' '. $text. ' (' . $lang->name . ')';
		}
		return $data ?? null;
	}
}
