<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

use Pivlu\Models\Language;

// Return first media url from a model
if (!function_exists('first_media_url')) {
	function first_media_url($model, $collection_name, $conversion_name = null)
	{
		return $model->getFirstMediaUrl($collection_name, $conversion_name);
	}
}

// Return avatar url
if (!function_exists('avatar')) {
	function avatar($user, $conversion_name = null)
	{
		if($conversion_name)
			return $user->getFirstMediaUrl('avatars', $conversion_name ?? 'thumb');
		else
			return $user->getFirstMediaUrl('avatars');
	}
}

// Return image url for a post
if (!function_exists('post_image')) {
	function post_image($model, $conversion_name = null)
	{
		if($conversion_name)
			return $model->getFirstMediaUrl('post_media', $conversion_name ?? 'small');
		else
			return $model->getFirstMediaUrl('post_media');
	}
}



// generate flag image from language code
if (!function_exists('flag')) {
	function flag($identificator)
	{
		if (is_int($identificator)) {
			$lang = Language::where('id', $identificator)->first();
			$code = $lang->code ?? null;
		} else
			$code = strtolower($identificator);


		$flag_url = asset('assets/img/flags/' . $code . '.svg');

		return '<img alt="' . $code . '" title="' . $code . '" class="img-flag" src=" ' . $flag_url . '">';
	}
}
