<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

use Pivlu\Models\Post;
use Pivlu\Models\PostTaxonomy;
use Pivlu\Models\PostTaxonomyRelation;
use Pivlu\Models\Block;
use Pivlu\Models\BlockType;

if (!function_exists('get_existing_taxonomies_list')) {
	function get_existing_taxonomies_list($post_id, $taxonomy_term_id)
	{
		//dd($post_id, $taxonomy_term_id);
		$data = [];
		$items = PostTaxonomyRelation::with('taxonomy')->where('post_id', $post_id)->where('post_type_taxonomy_id', $taxonomy_term_id)->get();
		if (count($items) == 0) return null;
		
		foreach ($items as $item) {
			//dd( $item->post_taxonomy_id, $item->taxonomy->default_language_content->name );
			$data[] = array('id' => $item->post_taxonomy_id, 'value' => $item->taxonomy->default_language_content->name);
		}

		return json_encode($data);
	}
}


if (!function_exists('get_taxonomies_list')) {
	function get_taxonomies_list($post_type_taxonomy_id)
	{
		//dd($post_type_taxonomy_id);

		//$items = Taxonomy::with('default_language')->where('taxonomy', $taxonomy)->where('active', 1)->orderBy('name')->pluck('name', 'id')->toArray();
		$items = PostTaxonomy::with('default_language_content')->where('post_type_taxonomy_id', $post_type_taxonomy_id)->where('active', 1)->get();
		
		$items_array = [];
		foreach ($items as $item) {
			$items_array[] = ['id' => $item->id, 'name' => $item->default_language_content->name];
			//$items_array = ['id' => $item->id, 'name' => $item->default_language_content->name];
		}

		//dd($items_array);
		return $items_array;
	}
}


// Get blocks for a specific content (post, page, sidebar, global (top / bottom sections), ....)
if (!function_exists('content_blocks')) {
	function content_blocks($post_id, $show_hidden = null)
	{

		if (!$show_hidden) {
			$blocks = Post::where('id', $post_id)->value('blocks');
			if (!$blocks) return array();
			$blocks = unserialize($blocks);
		} else {
			$blocks = Block::where('post_id', $post_id);

			if (!$show_hidden) $blocks = $blocks->where('blocks.hide', 0);

			$blocks = $blocks->orderBy('position')->get();
			if (!$blocks) return array();
		}

		return $blocks ?? array();
	}
}



// create breadcrumb for categories
if (!function_exists('breadcrumb_items')) {
	function breadcrumb_items($categ_id, $module = null)
	{
		if ($module == 'posts' || !$module) {
			$categ = PostCateg::where('id', $categ_id)->first();
			$title = $categ->title;
			$slug = $categ->slug;
		}

		if (!$categ) return array();

		$items[] = array('id' => $categ->id, 'title' => $title, 'slug' => $slug, 'url' => $categ->url, 'active' => $categ->active, 'icon' => $categ->icon, 'count_tree_posts' => $categ->count_tree_posts ?? null, 'count_tree_topics' => $categ->count_tree_topics ?? null, 'count_tree_posts' => $categ->count_tree_posts ?? null);

		$parent_id = $categ->parent_id;
		if ($parent_id) {
			$items = array_merge($items, breadcrumb_items($parent_id, $module));
		}

		$items = json_decode(json_encode($items)); // array to object;
		return ($items);
	}
}


if (!function_exists('breadcrumb')) {
	function breadcrumb($categ_id, $module = null)
	{
		if (!$categ_id)
			return array();
		if (!is_array(breadcrumb_items($categ_id, $module)))
			return array();

		return array_reverse(breadcrumb_items($categ_id, $module));
	}
}



// Generate table of content links for a post 
if (!function_exists('post_toc')) {
	function post_toc($id)
	{
		$block_type_id = BlockType::where('type', 'post_section')->value('id');

		$items = [];

		$sections = Block::with('active_language_content')->where(['post_id' => $id, 'type_id' => $block_type_id, 'hidden' => 0])->orderBy('position')->get();
		foreach($sections as $section) {
			$section_content = json_decode($section->active_language_content->content);			
			$items[] = ['title' => $section_content->title, 'slug' => $section_content->slug];
		}

		return $items;
	}
}
