<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace Pivlu\Cms\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Pivlu\Cms\Models\Config;
use Pivlu\Cms\Models\ConfigLang;
use Pivlu\Cms\Models\Language;

class ConfigController extends Controller
{

    /**
     * Config settings.
     */
    public function index(Request $request)
    {
        $tab = $request->tab ?? 'plugins';

        //if (!file_exists(resource_path('/views/admin/config/' . $tab . '.blade.php'))) return redirect(route('admin'));

        return view('pivlu::admin.index', [
            'view_file' => 'admin.config.' . $tab,
            'nav_section' => 'website',
            'active_menu' => 'config',
            'active_submenu' => 'website',
            'active_tab' => $tab,
            'seo_module' => $seo_module ?? null,
            'seo_configs' => $seo_configs ?? null,
            'langs' => Language::get_languages(),
        ]);
    }

    /**
     * Update config
     */
    public function update_config(Request $request)
    {
        $inputs = $request->except('_token');

        Config::update_config($inputs);

        return back()->with('success', 'updated');
    }


    /**
     * Update config lang
     */
    public function update_config_lang(Request $request)
    {
        $inputs = $request->except('_token');

        foreach ($inputs as $key => $value) {
            $array = explode('_', $key, 2);
            $lang_id = $array[0];
            $name = $array[1];
            if ($lang_id) ConfigLang::update_config($lang_id, $name, $value);
        }

        return back()->with('success', 'updated');
    }
}
