<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace Pivlu\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Pivlu\Models\ThemeNav;
use Pivlu\Models\ThemeNavRow;
use Pivlu\Models\ThemeNavItem;
use Pivlu\Models\ThemeStyle;
use Pivlu\Models\ThemeNavItemContent;
use Pivlu\Models\ThemeMenu;
use Pivlu\Models\Language;
use Pivlu\Functions\HelperFunctions;

class ThemeNavController extends Controller
{

    /**
     * Show all resources
     */
    public function index()
    {
        $navs = ThemeNav::orderByDesc('is_default')->orderBy('label')->paginate(25);

        return view('pivlu::admin.index', [
            'view_file' => 'admin.theme.navs.index',
            'active_menu' => 'appearance',
            'active_submenu' => 'navs',
            'nav_tab' => 'navs',
            'navs' => $navs,
        ]);
    }


    /**
     * Create resource
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'label' => 'required',
        ]);

        if ($validator->fails()) return redirect(route('admin.theme-navs.index'))->withErrors($validator)->withInput();

        if (ThemeNav::where('label', $request->label)->exists()) return redirect(route('admin.theme-navs.index'))->with('error', 'duplicate');

        $nav = ThemeNav::create([
            'label' => $request->label,
        ]);

        return redirect(route('admin.theme-navs.show', ['id' => $nav->id]))->with('success', 'created');
    }


    /**
     * Show resource
     */
    public function show(Request $request)
    {

        $nav = ThemeNav::find($request->id);
        if (!$nav) return redirect(route('admin.theme-navs.index'));

        $rows = ThemeNavRow::with('style')->where('nav_id', $nav->id)->orderBy('position')->get();

        return view('pivlu::admin.index', [
            'view_file' => 'admin.theme.navs.show',
            'active_menu' => 'appearance',
            'active_submenu' => 'navs',
            'nav_tab' => 'navs',
            'nav' => $nav,
            'rows' => $rows,
        ]);
    }


    /**
     * Remove the specified resource
     */
    public function destroy(Request $request)
    {
        $nav = ThemeNav::find($request->id);
        if (!$nav) return redirect(route('admin.theme-navs.index'));

        if ($nav->is_default == 1) return redirect(route('admin.theme-navs.index'));

        ThemeNav::where('id', $request->id)->delete();
        ThemeNavRow::where('nav_id', $request->id)->delete();
        ThemeNavItem::where('nav_id', $request->id)->delete();
        ThemeNavItemContent::where('nav_id', $request->id)->delete();

        return redirect(route('admin.theme-navs.index'))->with('success', 'deleted');
    }


    public function create_nav_row(Request $request)
    {
        $nav = ThemeNav::find($request->nav_id);
        if (!$nav) return redirect(route('admin.theme-navs.index'));

        ThemeNavRow::create([
            'nav_id' => $nav->id,
            'position' => (ThemeNavRow::where('nav_id', $nav->id)->max('position') ?? 0) + 1,
            'active' => 0,
        ]);

        return redirect(route('admin.theme-navs.show', ['id' => $nav->id]))->with('success', 'created');
    }


    public function show_nav_row(Request $request)
    {
        $nav = ThemeNav::find($request->nav_id);
        if (!$nav) return redirect(route('admin.theme-navs.index'));

        $row = ThemeNavRow::find($request->row_id);
        if (!$row) return redirect(route('admin.theme-navs.show', ['id' => $nav->id]));

        $row_items = ThemeNavItem::where(['row_id' => $row->id])->orderBy('position')->get();

        return view('pivlu::admin.index', [
            'view_file' => 'admin.theme.navs.show-row',
            'active_menu' => 'appearance',
            'active_submenu' => 'navs',
            'nav_tab' => 'navs',
            'nav' => $nav,
            'row' => $row,
            'row_items' => $row_items,
            'styles' => ThemeStyle::orderByDesc('is_default')->orderBy('label')->get(),
        ]);
    }


    public function destroy_nav_row(Request $request)
    {
        $nav = ThemeNav::find($request->nav_id);
        if (!$nav) return redirect(route('admin.theme-navs.index'));

        $row = ThemeNavRow::find($request->row_id);
        if (!$row) return redirect(route('admin.theme-navs.show', ['id' => $nav->id]));

        ThemeNavRow::where('id', $row->id)->delete();

        return redirect(route('admin.theme-navs.show', ['id' => $nav->id]))->with('success', 'deleted');
    }


    public function sortable_nav_rows(Request $request)
    {
        $i = 1;

        $items = $request->all();

        foreach ($items['item'] as $key => $value) {

            ThemeNavRow::where('nav_id', $request->nav_id)->where('id', $value)
                ->update([
                    'position' => $i,
                ]);

            $i++;
        }
    }


    public function nav_row_status(Request $request)
    {
        $nav = ThemeNav::find($request->nav_id);
        if (! $nav) return redirect(route('admin.theme-navs.index'));

        $row = ThemeNavRow::where('id', $request->row_id)->where('nav_id', $nav->id)->first();
        if (! $row) return redirect(route('admin.theme-navs.index'));

        $active = $request->active ? 1 : 0;
        
        $row->update([
            'active' => $active,
        ]);

        return redirect(route('admin.theme-navs.show', ['id' => $nav->id]))->with('success', 'updated');
    }


    public function store_row_item(Request $request)
    {
        $nav = ThemeNav::find($request->nav_id);
        if (! $nav) return redirect(route('admin.theme-navs.index'));

        $row = ThemeNavRow::where('id', $request->row_id)->where('nav_id', $nav->id)->first();
        if (! $row) return redirect(route('admin.theme-navs.index'));

        $column = $request->column;
        if (! in_array($column, ['left', 'center', 'right'])) return redirect(route('admin.theme-navs.show', ['id' => $nav->id]));

        $item_type = $request->item_type;
        if (! in_array($item_type, ['menu_links', 'logo', 'html', 'search', 'social_buttons', 'custom_code', 'login_register', 'language_switcher'])) return redirect(route('admin.theme-navs.show', ['id' => $nav->id]));

        ThemeNavItem::create([
            'nav_id' => $nav->id,
            'row_id' => $row->id,
            'column' => $column,
            'type' => $item_type,
            'position' => ThemeNavItem::where(['nav_id' => $nav->id, 'row_id' => $row->id, 'column' => $column])->max('position') + 1,
            'active' => 1,
        ]);

        return redirect(route('admin.theme-nav-rows.show', ['nav_id' => $nav->id, 'row_id' => $row->id]))->with('success', 'updated');
    }


    public function sortable_row_items(Request $request)
    {
        $nav = ThemeNav::find($request->nav_id);
        if (! $nav) return redirect(route('admin.theme-navs.index'));

        $row = ThemeNavRow::where('id', $request->row_id)->where('nav_id', $nav->id)->first();
        if (! $row) return redirect(route('admin.theme-navs.index'));

        $column = $request->column;
        if (! in_array($column, ['left', 'center', 'right'])) return redirect(route('admin.themes.show', ['id' => $theme->id]));

        $i = 1;
        $records = $request->all();

        foreach ($records['item'] as $key => $value) {
            ThemeNavItem::where('nav_id', $nav->id)
                ->where('row_id', $row->id)
                ->where('column', $column)
                ->where('id', $value)
                ->update([
                    'position' => $i,
                ]);

            $i++;
        }

        return;
    }


    public function show_nav_item(Request $request)
    {
        $nav = ThemeNav::find($request->nav_id);
        if (! $nav) return redirect(route('admin.theme-navs.index'));

        $row = ThemeNavRow::where('id', $request->row_id)->where('nav_id', $nav->id)->first();
        if (! $row) return redirect(route('admin.theme-navs.index'));

        $item = ThemeNavItem::where(['nav_id' => $nav->id, 'id' => $request->item_id])->first();
        if (! $item) return redirect(route('admin.theme-navs.show', ['nav_id' => $nav->id]));

        return view('pivlu::admin.index', [
            'view_file' => 'admin.theme.navs.show-row-item',
            'active_menu' => 'appearance',
            'active_submenu' => 'navs',
            'nav' => $nav,
            'row' => $row,
            'item' => $item,
            'menu_links' => ThemeMenu::orderByDesc('is_default')->orderBy('label')->get(),
        ]);
    }


    public function update_nav_item(Request $request)
    {
        $nav = ThemeNav::find($request->nav_id);
        if (! $nav) return redirect(route('admin.theme-navs.index'));

        $row = ThemeNavRow::where('id', $request->row_id)->where('nav_id', $nav->id)->first();
        if (! $row) return redirect(route('admin.theme-navs.index'));

        $item = ThemeNavItem::where(['nav_id' => $nav->id, 'id' => $request->item_id])->first();
        if (! $item) return redirect(route('admin.theme-navs.show', ['nav_id' => $nav->id]));

        if ($item->type == 'menu_links') {
            $item->update(['menu_links_id' => $request->menu_links_id ?? null]);
        }

        if ($item->type == 'html') {
            foreach (Language::get_languages() as $language) {
                $key_content = 'html_content_' . $language->id ?? null;

                $data = array(
                    'html_content' => HelperFunctions::clean_text($request->$key_content ?? null),
                );

                $item_content = ThemeNavItemContent::updateOrCreate(
                    [
                        'nav_id' => $request->nav_id,
                        'row_id' => $request->row_id,
                        'nav_item_id' => $item->id,
                        'lang_id' => $language->id
                    ],
                    ['data' => json_encode($data, JSON_UNESCAPED_UNICODE)]
                );
            }
        }

        if ($item->type == 'social_buttons') {
            $social_links = [];
            $names = $request->input('name', []);
            $icons = $request->input('icon', []);
            $urls = $request->input('url', []);

            for ($i = 0; $i < count($names); $i++) {
                if (($icons[$i] ?? null) && ($urls[$i] ?? null) && ($names[$i] ?? null)) {
                    $social_links[] = [
                        'name' => trim($names[$i]),
                        'icon' => trim($icons[$i]),
                        'url' => trim($urls[$i]),
                    ];
                }
            }

            if (count($social_links) == 0) {
                $social_links = null;
            }

            ThemeNavItem::where('id', $item->id)->update(
                [
                    'settings' => $social_links ? json_encode($social_links, JSON_UNESCAPED_UNICODE) : null
                ]
            );
        }


        if ($item->type == 'search') {
            $use_icon = $request->has('use_icon') ? 1 : 0;
            $search_input_size = $request->search_input_size;
            $search_input_min_width = $request->search_input_min_width;

            $settings = [
                'use_icon' => $use_icon,
                'search_input_size' => $search_input_size,
                'search_input_min_width' => $search_input_min_width,
            ];

            // update nav item settings
            ThemeNavItem::where('id', $item->id)->update(
                [
                    'settings' => json_encode($settings, JSON_UNESCAPED_UNICODE)
                ]
            );

            // update nav item content for each language
            foreach (Language::get_languages() as $language) {
                $key_button_text = 'search_button_text_' . $language->id ?? null;
                $key_placeholder_text = 'search_placeholder_text_' . $language->id ?? null;

                $data_button_text = array(
                    'search_button_text' => trim($request->$key_button_text ?? null),
                );

                $data_placeholder_text = array(
                    'search_placeholder_text' => trim($request->$key_placeholder_text ?? null),
                );

                $data = array_merge($data_button_text, $data_placeholder_text);

                ThemeNavItemContent::updateOrCreate(
                    [
                        'nav_id' => $request->nav_id,
                        'row_id' => $request->row_id,
                        'nav_item_id' => $item->id,
                        'lang_id' => $language->id
                    ],
                    ['data' => json_encode($data, JSON_UNESCAPED_UNICODE)]
                );
            }
        }

        if ($item->type == 'custom_code') {
            foreach (Language::get_languages() as $language) {
                $key_content = 'content_' . $language->id ?? null;

                $data = array(
                    'content' => HelperFunctions::clean_text($request->$key_content ?? null),
                );

                $item_content = ThemeNavItemContent::updateOrCreate(
                    [
                        'nav_id' => $request->nav_id,
                        'row_id' => $request->row_id,
                        'nav_item_id' => $item->id,
                        'lang_id' => $language->id
                    ],
                    ['data' => json_encode($data, JSON_UNESCAPED_UNICODE)]
                );
            }
        }

        return redirect(route('admin.theme-nav-row.show-item', ['nav_id' => $nav->id, 'row_id' => $row->id, 'item_id' => $item->id]))->with('success', 'updated');
    }


    public function delete_nav_item(Request $request)
    {
        $nav = ThemeNav::find($request->nav_id);
        if (! $nav) return redirect(route('admin.theme-navs.index'));

        $row = ThemeNavRow::where('id', $request->row_id)->where('nav_id', $nav->id)->first();
        if (! $row) return redirect(route('admin.theme-navs.index'));

        ThemeNavItem::where('id', $request->item_id)->delete();

        return redirect(route('admin.theme-nav-rows.show', ['nav_id' => $nav->id, 'row_id' => $row->id]))->with('success', 'deleted');
    }
}
