<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace Pivlu\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Pivlu\Models\ThemeStyle;
use Pivlu\Functions\ThemeFunctions;

class ThemeStyleController extends Controller
{

    /**
     * Show all resources
     */
    public function index()
    {

        $styles = ThemeStyle::orderByDesc('is_default')->orderBy('label')->paginate(20);

        return view('pivlu::admin.index', [
            'view_file' => 'admin.theme.styles.index',
            'active_menu' => 'appearance',
            'active_submenu' => 'styles',
            'nav_tab' => 'styles',
            'styles' => $styles,
        ]);
    }


    /**
     * Create resource
     */
    public function store(Request $request)
    {

        $validator = Validator::make($request->all(), [
            'label' => 'required',
        ]);

        if ($validator->fails()) return redirect(route('admin.theme-styles.index'))->withErrors($validator)->withInput();

        if (ThemeStyle::where('label', $request->label)->exists()) return redirect(route('admin.theme-styles.index'))->with('error', 'duplicate');

        $style = ThemeStyle::create([
            'label' => $request->label,
        ]);

        $source_style_id = $request->source_style_id;
        if ($source_style_id) {
            $source = ThemeStyle::find($source_style_id);
            if ($source) {

                ThemeStyle::updateOrCreate(['id' => $style->id], [
                    'data' => $source->data
                ]);
            }
        }

        // regenerate custom styles css file
        ThemeFunctions::generate_styles_css();

        return redirect(route('admin.theme-styles.show', ['id' => $style->id]))->with('success', 'created');
    }



    /**
     * Show resource
     */
    public function show(Request $request)
    {
        $style = ThemeStyle::find($request->id);
        if (! $style) return redirect(route('admin.theme-styles.index'));

        $item = json_decode($style->data);

        return view('pivlu::admin.index', [
            'view_file' => 'admin.theme.styles.show',
            'active_menu' => 'appearance',
            'active_submenu' => 'styles',
            'nav_tab' => 'styles',
            'style' => $style,
            'item' => $item,
            'fonts' => ThemeFunctions::fonts(),
            'font_sizes' => ThemeFunctions::font_sizes(),
        ]);
    }


    public function preview_style(Request $request)
    {
        $style = ThemeStyle::find($request->id);
        if (! $style) return redirect(route('admin.theme-styles.index'));

        return view('pivlu::admin.preview-style', [
            'style' => $style,
        ]);
    }


    /**
     * Update style
     */
    public function update(Request $request)
    {
        $style = ThemeStyle::find($request->id);
        if (! $style) return redirect(route('admin.theme-styles.index'));
        
        $data =  [
            'text_size' => $request->text_size,
            'text_color' => $request->text_color,
            'text_font_weight' => $request->text_font_weight,
            'text_align' => $request->text_align,
            'link_color' => $request->link_color,
            'link_hover_color' => $request->link_hover_color,
            'link_underline_color' => $request->link_underline_color,
            'link_underline_color_hover' => $request->link_underline_color_hover,
            'link_decoration' => $request->link_decoration,
            'link_hover_decoration' => $request->link_hover_decoration,
            'link_font_weight' => $request->link_font_weight,
            'link_underline_thickness' => $request->link_underline_thickness,
            'link_underline_offset' => $request->link_underline_offset,            
            'title_size' => $request->title_size,
            'subtitle_size' => $request->subtitle_size,
            'title_font_weight' => $request->title_font_weight,
            'subtitle_font_weight' => $request->subtitle_font_weight,            
            'caption_color' => $request->caption_color,
            'caption_size' => $request->caption_size,
            'caption_style' => $request->caption_style,
        ];

        if($request->has('use_custom_bg')) $data['bg_color'] = $request->bg_color;        
        if($request->has('use_custom_font_family')) $data['font_family'] = $request->font_family;
            
        $style->update(['data' => json_encode($data)]);

        // regenerate custom styles css file
        ThemeFunctions::generate_styles_css();

        return redirect(route('admin.theme-styles.show', ['id' => $request->id]))->with('success', 'updated');
    }



    /**
     * Remove the specified resource
     */
    public function destroy(Request $request)
    {

        $style = ThemeStyle::find($request->id);
        if (!$style) return redirect(route('admin.theme-styles.index'));

        ThemeStyle::where('id', $request->id)->delete();

        // regenerate css file
        ThemeFunctions::generate_styles_css();

        return redirect(route('admin.theme-styles.index'))->with('success', 'deleted');
    }
}
