<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

use Pivlu\Http\Controllers\Admin\AjaxController;
use Pivlu\Http\Controllers\Admin\AccountController;
use Pivlu\Http\Controllers\Admin\AccountInternalNoteController;
use Pivlu\Http\Controllers\Admin\AccountRoleController;
use Pivlu\Http\Controllers\Admin\AccountInvitationController;
use Pivlu\Http\Controllers\Admin\ConfigController;
use Pivlu\Http\Controllers\Admin\DashboardController;
use Pivlu\Http\Controllers\Admin\TrashController;

use Pivlu\Http\Controllers\Admin\BlockController;
use Pivlu\Http\Controllers\Admin\FormController;
use Pivlu\Http\Controllers\Admin\LangController;
use Pivlu\Http\Controllers\Admin\PackageController;
use Pivlu\Http\Controllers\Admin\PostTypeController;
use Pivlu\Http\Controllers\Admin\PostTypeTaxonomyController;
use Pivlu\Http\Controllers\Admin\PostController;
use Pivlu\Http\Controllers\Admin\PostTaxonomyController;
use Pivlu\Http\Controllers\Admin\ThemeController;
use Pivlu\Http\Controllers\Admin\ThemeFooterController;
use Pivlu\Http\Controllers\Admin\ThemeHomepageController;
use Pivlu\Http\Controllers\Admin\ThemeNavController;
use Pivlu\Http\Controllers\Admin\ThemeButtonController;
use Pivlu\Http\Controllers\Admin\ThemeMenuController;
use Pivlu\Http\Controllers\Admin\ThemeStyleController;

Route::get('/', [DashboardController::class, 'index'])->name('admin');

Route::name('admin.')->group(function () {
    // Dashboard
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Roles and permissions
    Route::resource('accounts/roles', AccountRoleController::class)->parameters(['roles' => 'role']);
    //Route::get('accounts/roles/{role}', [AccountRoleController::class, 'permissions'])->where('role', '[a-zA-Z0-9_]+')->name('roles.permissions');
    //Route::post('accounts/roles/{role}', [AccountController::class, 'update_permissions']);

    Route::get('accounts/invitations', [AccountInvitationController::class, 'index'])->name('accounts.invitations');
    Route::post('accounts/send-invitation', [AccountInvitationController::class, 'send'])->name('accounts.send_invitation');
    Route::post('accounts/resend-invitation', [AccountInvitationController::class, 'resend'])->name('accounts.resend_invitation');
    Route::delete('accounts/delete-invitation', [AccountInvitationController::class, 'destroy'])->name('accounts.delete_invitation');

    // Accounts
    Route::resource('accounts', AccountController::class)->parameters(['accounts' => 'id']);

    Route::get('account/{id}/block', [AccountController::class, 'block'])->where('id', '[0-9]+')->name('account.block');
    Route::post('account/{id}/action/{action}', [AccountController::class, 'action'])->where('id', '[0-9]+')->where('action', '[a-zA-Z0-9]+')->name('account.action');

    Route::get('account/{id}/reset-password', [AccountController::class, 'reset_password'])->where('id', '[0-9]+')->name('account.reset_password');
    Route::post('account/{id}/reset-password', [AccountController::class, 'reset_password_action'])->where('id', '[0-9]+');

    Route::resource('accounts.internal-notes', AccountInternalNoteController::class)->parameters(['accounts' => 'account_id', 'internal-notes' => 'note_id'])->shallow();

    // Posts
    Route::resource('post-types', PostTypeController::class)->parameters(['post-types' => 'id']);
    Route::resource('post-type-taxonomies', PostTypeTaxonomyController::class)->parameters(['post-type-taxonomies' => 'id']);
    Route::resource('post-taxonomies', PostTaxonomyController::class)->parameters(['post-taxonomies' => 'id']);

    Route::resource('posts', PostController::class)->parameters(['posts' => 'id']);
    Route::post('posts/{id}/sortable', [PostController::class, 'sortable'])->name('posts.sortable')->where('id', '[0-9]+');
    Route::get('posts/{id}/content', [PostController::class, 'content'])->name('posts.content')->where('id', '[0-9]+');
    Route::post('posts/{id}/content', [PostController::class, 'update_content'])->name('posts.content.new')->where('id', '[0-9]+');
    Route::delete('posts/{id}/content/delete/{block_id}', [PostController::class, 'delete_content'])->name('posts.content.delete')->where('id', '[0-9]+')->where('block_id', '[0-9]+');
    Route::get('posts/{id}/delete-main-image', [PostController::class, 'delete_main_image'])->name('posts.delete_main_image')->where('id', '[0-9]+');

    // Theme Menus
    Route::resource('appearance/theme-menus', ThemeMenuController::class)->parameters(['theme-menus' => 'id']);
    Route::post('appearance/theme-menu/{menu_id}/item/create', [ThemeMenuController::class, 'store_item'])->name('theme-menus.item.create')->where('menu_id', '[0-9]+');
    Route::put('appearance/theme-menu/item/update/{item_id}', [ThemeMenuController::class, 'update_item'])->name('theme-menus.item.update')->where('item_id', '[0-9]+');
    Route::delete('appearance/theme-menu/item/delete/{item_id}', [ThemeMenuController::class, 'delete_item'])->name('theme-menus.item.delete')->where('item_id', '[0-9]+');
    Route::post('appearance/theme-menu/{menu_id}/items/sortable', [ThemeMenuController::class, 'sortable'])->name('theme-menus.items.sortable')->where('menu_id', '[0-9]+');

    Route::get('appearance/theme-menu/{parent_id}/dropdown', [ThemeMenuController::class, 'index_dropdown'])->name('theme-menu.dropdown')->where(['parent_id' => '[0-9]+']);
    Route::post('appearance/theme-menu/{parent_id}/dropdown', [ThemeMenuController::class, 'store_dropdown'])->where(['parent_id' => '[0-9]+']);
    Route::put('appearance/theme-menu/{parent_id}/dropdown/update/{item_id}', [ThemeMenuController::class, 'update_dropdown'])->name('theme-menu.dropdown.update')->where(['parent_id' => '[0-9]+', 'item_id' => '[0-9]+']);
    Route::delete('appearance/theme-menu/{parent_id}/dropdown/delete/{item_id}', [ThemeMenuController::class, 'destroy_dropdown'])->name('theme-menu.dropdown.delete')->where(['parent_id' => '[0-9]+', 'item_id' => '[0-9]+']);
    Route::post('appearance/theme-menu/{parent_id}/dropdown/sortable', [ThemeMenuController::class, 'sortable_dropdown'])->name('theme-menu.dropdown.sortable')->where(['parent_id' => '[0-9]+']);

    // Theme Footers
    Route::resource('appearance/theme-footers', ThemeFooterController::class)->parameters(['theme-footers' => 'id']);
    Route::get('appearance/theme-footers/{id}/{destination}/content', [ThemeFooterController::class, 'content'])->name('theme-footers.content')->where(['id' => '[0-9]+', 'destination' => '[a-z]+']);

    Route::post('appearance/theme-footers/{footer_id}/{destination}/content', [ThemeFooterController::class, 'update_content'])->where(['footer_id' => '[0-9]+', 'destination' => '[a-z0-9_-]+']);
    Route::post('appearance/theme-footers/{footer_id}/{destination}/{col}/sortable', [ThemeFooterController::class, 'sortable'])->name('theme-footer.sortable')->where(['footer_id' => '[0-9]+', 'destination' => '[a-z0-9_-]+', 'col' => '[0-9]+']);
    Route::delete('appearance/theme-footers/{footer_id}/delete/{block_id}', [ThemeFooterController::class, 'delete_content'])->name('theme-footer.content.delete')->where(['footer_id' => '[0-9]+', 'block_id' => '[0-9]+']);

    // Theme Navs
    Route::resource('appearance/theme-navs', ThemeNavController::class)->parameters(['theme-navs' => 'id']);
    Route::get('appearance/theme-nav-rows/create', [ThemeNavController::class, 'create_nav_row'])->name('theme-nav-rows.create');    
    Route::post('appearance/theme-nav-rows/sortable', [ThemeNavController::class, 'sortable_nav_rows'])->name('theme-nav-rows.sortable');    
    Route::get('appearance/theme-nav/{nav_id}/{row_id}', [ThemeNavController::class, 'show_nav_row'])->name('theme-nav-rows.show')->where(['nav_id' => '[0-9]+', 'row_id' => '[0-9]+']);    
    Route::put('appearance/theme-nav/{nav_id}/{row_id}/status', [ThemeNavController::class, 'nav_row_update'])->name('theme-nav-row.update')->where(['nav_id' => '[0-9]+', 'row_id' => '[0-9]+']);    
    Route::delete('appearance/theme-nav/{nav_id}/{row_id}/delete', [ThemeNavController::class, 'destroy_nav_row'])->name('theme-nav-rows.delete')->where(['nav_id' => '[0-9]+', 'row_id' => '[0-9]+']);    
    Route::get('appearance/theme-nav/{nav_id}/{row_id}/add-item/{column}/{item_type}', [ThemeNavController::class, 'store_row_item'])->name('theme-nav-rows.add-item')->where(['nav_id' => '[0-9]+', 'row_id' => '[0-9]+', 'column' => '[a-zA-Z0-9_-]+', 'item_type' => '[a-zA-Z0-9_-]+']);
    Route::post('appearance/theme-nav/{nav_id}/{row_id}/{column}/sortable', [ThemeNavController::class, 'sortable_row_items'])->name('theme-nav-rows.sortable-item')->where(['nav_id' => '[0-9]+', 'row_id' => '[0-9]+', 'column' => '[a-zA-Z0-9_-]+']);
    Route::get('appearance/theme-nav/{nav_id}/{row_id}/item/{item_id}', [ThemeNavController::class, 'show_nav_item'])->name('theme-nav-row.show-item')->where(['nav_id' => '[0-9]+', 'row_id' => '[0-9]+', 'item_id' => '[0-9]+']);
    Route::put('appearance/theme-nav/{nav_id}/{row_id}/item/{item_id}', [ThemeNavController::class, 'update_nav_item'])->name('theme-nav-row.update-item')->where(['nav_id' => '[0-9]+', 'row_id' => '[0-9]+', 'item_id' => '[0-9]+']);
    Route::delete('appearance/theme-nav/{nav_id}/{row_id}/delete/{item_id}', [ThemeNavController::class, 'delete_nav_item'])->name('theme-nav-row.delete-item')->where(['nav_id' => '[0-9]+', 'row_id' => '[0-9]+', 'item_id' => '[0-9]+']);
    

    // Themes
    Route::resource('appearance/themes', ThemeController::class)->parameters(['themes' => 'id']);
    Route::get('appearance/theme-set-active/{id}', [ThemeController::class, 'set_active'])->name('themes.set-active')->where('id', '[0-9]+');    

    Route::post('appearance/theme/{id}/update-homepage-block', [ThemeHomepageController::class, 'update_block'])->name('theme.homepage.blocks.store')->where('id', '[0-9]+');
    Route::delete('appearance/theme/{id}/delete-homepage-block', [ThemeHomepageController::class, 'delete_block'])->name('theme.homepage.blocks.delete')->where('id', '[a-zA-Z0-9_-]+');
    Route::post('appearance/theme/sortable-homepage-blocks/{theme_id}', [ThemeHomepageController::class, 'sortable_blocks'])->name('theme.homepage.blocks.sortable')->where('theme_id', '[0-9]+');
    Route::post('appearance/theme/{id}/update-logo', [ThemeController::class, 'update_logo'])->name('theme.logo')->where('id', '[0-9]+');

    // Theme Styles
    Route::resource('appearance/theme-styles', ThemeStyleController::class)->parameters(['theme-styles' => 'id']);
    Route::get('preview-style/{id}', [ThemeStyleController::class, 'preview_style'])->name('preview-style')->where('id', '[a-z0-9_-]+');

    // Theme Buttons
    Route::resource('appearance/theme-buttons', ThemeButtonController::class)->parameters(['theme-buttons' => 'id']);

    // Theme custom code
    Route::get('appearance/theme-custom-code', [ThemeController::class, 'custom_code'])->name('theme-custom-code');
    Route::post('appearance/theme-custom-code', [ThemeController::class, 'update_custom_code']);

    // Blocks routes
    Route::resource('blocks', BlockController::class)->parameters(['blocks' => 'id']);
    Route::post('block-items/{type}/{block_id}', [BlockController::class, 'store_item'])->name('block.store-item')->where(['type' => '[a-zA-Z0-9]+', 'block_id' => '[0-9]+']);
    Route::put('block-items/{type}/{block_id}', [BlockController::class, 'update_item'])->name('block.update-item')->where(['type' => '[a-zA-Z0-9]+', 'block_id' => '[0-9]+']);
    Route::post('block-items/{type}/{block_id}/sortable', [BlockController::class, 'sortable_items'])->name('block.sortable-items')->where(['type' => '[a-zA-Z0-9]+', 'block_id' => '[0-9]+']);
    Route::delete('block-items/delete/{block_item_id}', [BlockController::class, 'destroy_item'])->name('block.delete-item')->where(['block_item_id' => '[0-9]+']);


    // Forms   
    Route::get('forms', [FormController::class, 'messages'])->name('forms');
    Route::get('forms/{id}', [FormController::class, 'show_message'])->name('forms.show')->where('id', '[0-9]+');
    Route::get('forms/{id}/to-trash', [FormController::class, 'message_to_trash'])->name('forms.to_trash')->where('id', '[0-9]+');
    Route::get('forms/{id}/mark', [FormController::class, 'message_mark'])->name('forms.mark')->where('id', '[0-9]+');
    Route::post('forms/multiple-action', [FormController::class, 'messages_multiple_action'])->name('forms.multiple_action');


    //  admins only
    Route::middleware('logged_is_admin')->group(function () {
        // Config
        Route::get('config/{tab}', [ConfigController::class, 'index'])->name('config')->where(['tab' => '[a-zA-Z0-9_-]+']);
        Route::post('config', [ConfigController::class, 'update_config'])->name('config.update');
        Route::post('config-lang', [ConfigController::class, 'update_config_lang'])->where(['tab' => '[a-zA-Z0-9_-]+'])->name('config-lang.update');

        // Packages
        Route::get('packages', [PackageController::class, 'index'])->name('packages');
        Route::post('packages', [PackageController::class, 'update']);

        // Forms
        Route::resource('forms/config', FormController::class)
            ->names(['index' => 'forms.config', 'create' => 'forms.config.create', 'show' => 'forms.config.show'])
            ->parameters(['config' => 'id']);
        Route::post('forms/config/{id}/add-field', [FormController::class, 'add_field'])->name('forms.config.add_field')->where('id', '[0-9]+');
        Route::put('forms/config/{id}/update-field/{field_id}', [FormController::class, 'update_field'])->name('forms.config.update_field')->where('id', '[0-9]+')->where('field_id', '[0-9]+');
        Route::delete('forms/config/{id}/delete-field/{field_id}', [FormController::class, 'destroy_field'])->name('forms.config.delete_field')->where('id', '[0-9]+')->where('field_id', '[0-9]+');
        Route::post('forms/config/{id}/sortable', [FormController::class, 'sortable'])->name('forms.config.sortable')->where('id', '[0-9]+');


        // Trash
        Route::get('trash', [TrashController::class, 'index'])->name('trash');
        Route::get('trash/empty/{module}', [TrashController::class, 'empty'])->name('trash.empty')->where('module', '[a-zA-Z0-9]+');
        Route::post('trash/multiple-action/{module}', [TrashController::class, 'multiple_action'])->name('trash.multiple_action')->where('module', '[a-zA-Z0-9]+');
        Route::get('trash/single-action/{module}/{id}', [TrashController::class, 'single_action'])->name('trash.single_action')->where('module', '[a-zA-Z0-9]+')->where('id', '[0-9]+');
        Route::get('trash/{module}', [TrashController::class, 'module'])->name('trash.module')->where('module', '[a-zA-Z0-9]+');

        Route::resource('languages', LangController::class)->parameters(['languages' => 'id']);
    });

    // Other routes
    Route::get('ajax/{source}', [AjaxController::class, 'index'])->name('ajax')->where('source', '[a-z0-9_-]+');
});
