<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\ToolsController as FrontendToolsController;

use App\Http\Controllers\Admin\AjaxController as BackendAjaxController;
use App\Http\Controllers\Admin\AccountController as BackendAccountController;
use App\Http\Controllers\Admin\AccountInternalNoteController as BackendAccountInternalNoteController;
use App\Http\Controllers\Admin\AccountRoleController as BackendAccountRoleController;
use App\Http\Controllers\Admin\BlockController as BackendBlockController;
use App\Http\Controllers\Admin\ConfigController as BackendConfigController;
use App\Http\Controllers\Admin\DashboardController as BackendDashboardController;
use App\Http\Controllers\Admin\FormController as BackendFormController;
use App\Http\Controllers\Admin\LangController as BackendLangController;
use App\Http\Controllers\Admin\ModuleController as BackendModuleController;
use App\Http\Controllers\Admin\PostTypeController as BackendPostTypeController;
use App\Http\Controllers\Admin\PostTypeTaxonomyController as BackendPostTypeTaxonomyController;
use App\Http\Controllers\Admin\PostController as BackendPostController;
use App\Http\Controllers\Admin\PostTaxonomyController as BackendPostTaxonomyController;
use App\Http\Controllers\Admin\RecycleBinController as BackendRecycleBinController;
use App\Http\Controllers\Admin\ThemeController as BackendThemeController;
use App\Http\Controllers\Admin\ThemeFooterController as BackendThemeFooterController;
use App\Http\Controllers\Admin\ThemeHomepageController as BackendThemeHomepageController;
use App\Http\Controllers\Admin\ThemeButtonController as BackendThemeButtonController;
use App\Http\Controllers\Admin\ThemeMenuController as BackendThemeMenuController;
use App\Http\Controllers\Admin\ThemeMenuDropdownController as BackendThemeMenuDropdownController;
use App\Http\Controllers\Admin\ThemeStyleController as BackendThemeStyleController;
use App\Http\Controllers\Admin\ThemeLayoutController as BackendThemeLayoutController;


/***********************************
 * FRONTEND ROUTES START
 ***********************************/

Route::get('/account', function () {
    if (Auth::user()) return redirect(route('admin'));
    else return redirect(route('login'));
})->name('account')->withoutMiddleware([CheckWebsiteMiddleware::class]); // IMPORTANT !!! Add ->withoutMiddleware() to avoid 'to many redirects' error

// Web maintenance
Route::get('maintenance-mode', [FrontendToolsController::class, 'maintenance'])->name('maintenance')->withoutMiddleware([CheckWebsiteMiddleware::class]); // IMPORTANT !!! Add ->withoutMiddleware() to avoid 'to many redirects' error

// Web New Account Invitation
Route::get('action/invite', [FrontendToolsController::class, 'account_invitation']);
Route::post('action/invite', [FrontendToolsController::class, 'account_invitation_submit']);


// 1. DEFAULT LANGUAGE
// Web Homepage
Route::get('/', [HomeController::class, 'index'])->name('home');


// 2. OTHER LANGUAGES
Route::prefix('{locale}')->name('locale.')->group(function () {
    // Web Homepage
    Route::get('/', [HomeController::class, 'index'])->name('home')->where(['locale' => '[a-z]{2,}+']);
});

/***********************************
 * FRONTEND ROUTES END
 ***********************************/


/***********************************
 * BACKEN ROUTES START
 ***********************************/
Route::get('account', [BackendDashboardController::class, 'dashboard'])->name('admin');

Route::prefix('account')->name('admin.')->group(function () {
    // Dashboard
    Route::get('dashboard', [BackendDashboardController::class, 'dashboard'])->name('dashboard');

    // Roles and permissions
    Route::resource('accounts/roles', BackendAccountRoleController::class)->parameters(['roles' => 'role']);
    //Route::get('accounts/roles/{role}', [AccountRoleController::class, 'permissions'])->where('role', '[a-zA-Z0-9_]+')->name('roles.permissions');
    //Route::post('accounts/roles/{role}', [AccountController::class, 'update_permissions']);

    // Accounts
    Route::resource('accounts', BackendAccountController::class)->parameters(['accounts' => 'id']);

    Route::get('account/{id}/block', [BackendAccountController::class, 'block'])->where('id', '[0-9]+')->name('account.block');
    Route::post('account/{id}/action/{action}', [BackendAccountController::class, 'action'])->where('id', '[0-9]+')->where('action', '[a-zA-Z0-9]+')->name('account.action');

    Route::get('account/{id}/reset-password', [BackendAccountController::class, 'reset_password'])->where('id', '[0-9]+')->name('account.reset_password');
    Route::post('account/{id}/reset-password', [BackendAccountController::class, 'reset_password_action'])->where('id', '[0-9]+');

    Route::resource('accounts.internal-notes', BackendAccountInternalNoteController::class)->parameters(['accounts' => 'account_id', 'internal-notes' => 'note_id'])->shallow();


    //  admin role only
    Route::middleware(LoggedIsAdminMiddleware::class)->group(function () {
        // Languages
        Route::resource('languages', BackendLangController::class)->parameters(['languages' => 'id']);

        // Config
        Route::get('config/{tab}', [BackendConfigController::class, 'index'])->name('config')->where(['tab' => '[a-zA-Z0-9_-]+']);
        Route::post('config/{tab}', [BackendConfigController::class, 'update'])->where(['tab' => '[a-zA-Z0-9_-]+']);
        Route::post('config-lang', [BackendConfigController::class, 'update_config_lang'])->where(['tab' => '[a-zA-Z0-9_-]+']);

        // Modules
        Route::get('modules', [BackendModuleController::class, 'index'])->name('modules');
        Route::post('modules', [BackendModuleController::class, 'update']);

        // Trash
        Route::get('trash', [BackendRecycleBinController::class, 'index'])->name('trash');
        Route::get('trash/empty/{module}', [BackendRecycleBinController::class, 'empty'])->name('trash.empty')->where('module', '[a-zA-Z0-9]+');
        Route::post('trash/multiple-action/{module}', [BackendRecycleBinController::class, 'multiple_action'])->name('trash.multiple_action')->where('module', '[a-zA-Z0-9]+');
        Route::get('trash/single-action/{module}/{id}', [BackendRecycleBinController::class, 'single_action'])->name('trash.single_action')->where('module', '[a-zA-Z0-9]+')->where('id', '[0-9]+');
        Route::get('trash/{module}', [BackendRecycleBinController::class, 'module'])->name('trash.module')->where('module', '[a-zA-Z0-9]+');
    });

});

/***********************************
 * BACKEN ROUTES END
 ***********************************/
