<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace Pivlu\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Pivlu\Models\User;
use Pivlu\Models\UserMeta;
use Pivlu\Models\Post;
use Pivlu\Models\Config;

class ProfileController extends Controller
{

    /**
     * Display static page
     */
    public function index(Request $request)
    {
        $username = $request->username;

        $user = User::where('username', $username)->first();
        if (!$user) return redirect(route('home'));

        $posts = Post::with('user', 'taxonomies', 'active_language_content', 'default_language_content', 'post_type')
            ->whereHas('post_type', function ($query) {
                $query->where('type', '!=', 'page');
            })
            ->where('user_id', $user->id)
            ->where('status', 'published')
            ->orderByDesc('id')
            ->paginate(Config::config()->posts_per_page ?? 12);

        return view('pivlu::web.profile', [
            'user' => $user,
            'bio' => UserMeta::get_meta($user->id, 'bio'),
            'posts' => $posts,
        ]);
    }
}
