<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('pivlu_posts', function (Blueprint $table) {
            $table->id();
            $table->char('type', 25);
            $table->unsignedBigInteger('media_id')->nullable();
            $table->unsignedBigInteger('user_id')->nullable();
            $table->integer('parent_id')->nullable(); // used for 'page' type only
            $table->string('status', 20);
            $table->boolean('sticky')->default(false);
            $table->integer('hits')->default(0);            
            $table->integer('reaction_count')->default(0);
            $table->integer('comment_count')->default(0);
            $table->integer('minutes_to_read')->default(0)->nullable();
            $table->boolean('disable_comments')->default(false);
            $table->boolean('disable_reactions')->default(false);            
            $table->boolean('is_homepage')->default(false);
            $table->mediumtext('blocks')->nullable();
            $table->timestamps();
            $table->softDeletes();
            
            $table->foreign('media_id')->references('id')->on('pivlu_media')->nullOnDelete();
            $table->foreign('user_id')->references('id')->on('users')->cascadeOnDelete();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('pivlu_posts');
        Schema::dropSoftDeletes();
    }
};
