<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('pivlu_blocks', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('type_id')->nullable();
            $table->unsignedBigInteger('post_id')->nullable();
            $table->unsignedBigInteger('media_id')->nullable();
            $table->unsignedBigInteger('theme_id')->nullable();
            $table->unsignedBigInteger('footer_id')->nullable();
            $table->unsignedBigInteger('layout_id')->nullable();    
            $table->boolean('is_homepage_block')->default(false)->index();
            $table->string('label', 100)->nullable();
            $table->integer('position')->default(0);
            $table->boolean('hidden')->default(false);
            $table->text('settings')->nullable();
            $table->tinyInteger('footer_col')->nullable();
            $table->string('footer_destination', 20)->nullable();
            $table->tinyInteger('footer_layout')->nullable();
            $table->tinyInteger('layout_section')->nullable();
            $table->unsignedBigInteger('user_id')->nullable();
            $table->timestamps();

            $table->foreign('type_id')->references('id')->on('pivlu_block_types')->nullOnDelete();
            $table->foreign('post_id')->references('id')->on('pivlu_posts')->cascadeOnDelete();
            $table->foreign('user_id')->references('id')->on('users')->nullOnDelete();
            $table->foreign('media_id')->references('id')->on('media')->nullOnDelete();
            $table->foreign('theme_id')->references('id')->on('pivlu_themes')->nullOnDelete();
            $table->foreign('footer_id')->references('id')->on('pivlu_theme_footers')->cascadeOnDelete();
            $table->foreign('layout_id')->references('id')->on('pivlu_theme_layouts')->cascadeOnDelete();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('pivlu_blocks');
    }
};
