<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

return [
    'common' => [
        'editor' => [
            'label' => 'Text editor',
            'icon' => '<i class="bi bi-textarea-t"></i>'
        ],
        'text' => [
            'label' => 'Simple text',
            'icon' => '<i class="bi bi-file-text"></i>'
        ],
        'image' => [
            'label' => 'Image / Banner',
            'icon' => '<i class="bi bi-image"></i>'
        ],
        'gallery' => [
            'label' => 'Images gallery',
            'icon' => '<i class="bi bi-images"></i>'
        ],
        'video' => [
            'label' => 'Video',
            'icon' => '<i class="bi bi-play-btn"></i>'
        ],
    ],

    'posts' => [
        'posts_content' => [
            'label' => 'Content from posts types',
            'icon' => '<i class="bi bi-card-checklist"></i>'
        ],
        'posts_taxonomies' => [
            'label' => 'Posts taxonomies',
            'icon' => '<i class="bi bi-diagram-3"></i>'
        ],
        'post_section' => [
            'label' => 'Post section',
            'icon' => '<i class="bi bi-distribute-vertical"></i>'
        ],
        'post_toc' => [
            'label' => 'Post Table of Content',
            'icon' => '<i class="bi bi-list-ol"></i>'
        ],
    ],

    'components' => [
        'form' => [
            'label' => 'Form',
            'icon' => '<i class="bi bi-input-cursor-text"></i>'
        ],
        'card' => [
            'label' => 'Card',
            'icon' => '<i class="bi bi-file-richtext"></i>'
        ],
        'hero' => [
            'label' => 'Hero',
            'icon' => '<i class="bi bi-card-heading"></i>'
        ],
        'slider' => [
            'label' => 'Slider',
            'icon' => '<i class="bi bi-collection"></i>'
        ],
        'accordion' => [
            'label' => 'Accordion',
            'icon' => '<i class="bi bi-menu-up"></i>'
        ],
    ],

    'miscellaneous' => [
        'custom' => [
            'label' => 'Custom',
            'icon' => '<i class="bi bi-code"></i>'
        ],
        'search' => [
            'label' => 'Search form',
            'icon' => '<i class="bi bi-search"></i>'
        ],
        'links' => [
            'label' => 'Links',
            'icon' => '<i class="bi bi-list-ul"></i>'
        ],
        'alert' => [
            'label' => 'Alert',
            'icon' => '<i class="bi bi-exclamation-square"></i>'
        ],
        'map' => [
            'label' => 'Google Map',
            'icon' => '<i class="bi bi-gep-alt"></i>'
        ],
        'include' => [
            'label' => 'Include file',
            'icon' => '<i class="bi bi-file-earmark-plus"></i>'
        ],
        'blockquote' => [
            'label' => 'Blockquote',
            'icon' => '<i class="bi bi-chat-left-quote"></i>'
        ],
        'testimonial' => [
            'label' => 'Testimonial',
            'icon' => '<i class="bi bi-star-half"></i>'
        ],
    ],

];
