<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace App\Functions;

use App\Models\PostType;
use App\Models\PostTypeContent;
use App\Models\PostTypeTaxonomy;
use App\Models\PostTypeTaxonomyContent;
use App\Models\Language;
use App\Models\Module;

class ModuleFunctions
{
    public static function setup_docs()
    {

        $docs_module = Module::where('slug', 'docs')->first();
        if (! $docs_module) return false;

        if (PostType::where('type', 'docs')->doesntExist()) {
            $post_type = PostType::create([
                'type' => 'docs',
                'show_in_admin_menu' => 1,
                'admin_menu_icon' => '<i class="bi-question-circle"></i>',
                'core' => 0,
                'active' => 1,
                'module_id' => $docs_module->id
            ]);

            $docs_labels = [
                "singular" => "Docs article",
                "plural" => "Docs articles",
                "create"  => "Create new article",
                "update"  => "Update article",
                "delete" => "Delete article",
                "all" => "All articles",
                "search" => "Search in articles"
            ];
            PostTypeContent::create([
                'post_type_id' => $post_type->id,
                'lang_id' => Language::get_default_language()->id,
                'name' => 'Knowledge Base',
                'slug' => 'docs',
                'labels' => json_encode($docs_labels, JSON_UNESCAPED_UNICODE),
            ]);

            $post_type_taxonomy = PostTypeTaxonomy::create([
                'post_type_id' => $post_type->id,
                'hierarchical' => 1,
                'active' => 1,
                'position' => 1,
                'admin_filter' => 1
            ]);

            $docs_taxonomy_labels = [
                "singular" => "Category",
                "plural" => "Categories",
                "create"  => "Create new category",
                "update"  => "Update category",
                "delete" => "Delete category",
                "all" => "All categories",
                "search" => "Search in categories"
            ];
            PostTypeTaxonomyContent::create([
                'post_type_taxonomy_id' => $post_type_taxonomy->id,
                'lang_id' => Language::get_default_language()->id,
                'name' => 'Categories',
                'slug' => 'category',
                'labels' => json_encode($docs_taxonomy_labels, JSON_UNESCAPED_UNICODE),
            ]);
        }
    }
}
