<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

use App\Models\Post;
use App\Models\PostCateg;
use App\Models\Language;
use App\Models\Config;


// Latest posts (all categories or category ID)
if (!function_exists('posts__')) {
	function posts__($categ_id = null)
	{

		$posts = Post::with('author', 'category')
			->where('status', 'published')
			->whereHas('category', function ($query) {
				$query->where('active', 1);
			})
			->where('lang_id', Language::get_active_language()->id ?? null);

		if ($categ_id) {
			$categ = PostCateg::where('id', $categ_id)->where('active', 1)->first();
			$categ_tree_ids = $categ->tree_ids ?? null;
			if ($categ_tree_ids) $categ_tree_ids_array = explode(',', $categ_tree_ids);
			$posts = $posts->whereIn('categ_id', $categ_tree_ids_array ?? array());
		}

		$posts = $posts->orderByDesc('posts.featured')
			->orderByDesc('posts.id')
			->paginate(Config::config()->posts_per_page ?? 24);

		return $posts;
	}
}
