<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace Pivlu\Functions;

use Illuminate\Support\Str;
use Pivlu\Models\Block;
use Pivlu\Models\BlockContent;
use Pivlu\Models\BlockType;
use Pivlu\Models\Post;
use Pivlu\Models\Language;
use Pivlu\Models\ThemeConfig;

class BlockFunctions
{

    /**
     * Get homepage blocks for a specific theme
     *
     * @param int|null $theme_id The ID of the theme to get homepage blocks for. If null, uses the active theme.
     * @return array An array of block IDs for the homepage.
     */
    public static function get_homepage_blocks($theme_id = null)
    {
        if ($theme_id === null) {
            $active_theme = ThemeFunctions::get_active_theme();
            if (! $active_theme) return [];
            $theme_id = $active_theme->id;
        }
        $blocks = ThemeConfig::get_theme_config($theme_id, 'homepage_blocks');
        if (! $blocks) return [];

        $blocks = json_decode($blocks);

        return $blocks ?? [];
    }



    /**
     * Regenerate blocks for a specific post
     *
     * @param int $post_id The ID of the post to regenerate blocks for
     * @return null
     */
    public static function regenerate_post_blocks($post_id)
    {
        $post = Post::find($post_id);
        if (!$post) return null;

        $blocks = Block::where(['post_id' => $post_id, 'hidden' => 0])->orderBy('position')->get();

        $blocks_array = [];
        foreach ($blocks as $block) {
            array_push($blocks_array, $block->id);
        }

        $post->update(['blocks' => json_encode($blocks_array)]);

        return;
    }


    /**
     * Regenerate homepage blocks for a specific theme
     *
     * @param int $theme_id The ID of the theme to regenerate homepage blocks for
     * @return null
     */
    public static function regenerate_homepage_blocks($theme_id)
    {
        $blocks = Block::with('block_type')
            ->where('is_homepage_block', 1)
            ->where('theme_id', $theme_id)
            ->where('hidden', 0)
            ->orderBy('position')
            ->get();

        $blocks_array = [];
        foreach ($blocks as $block) {
            array_push($blocks_array, $block->id);
        }

        ThemeConfig::update_config($theme_id, 'homepage_blocks', json_encode($blocks_array));

        return;
    }



    /**
     * Update an existing block's settings and associated content based on its type.
     *
     * This method retrieves the block and its type, then applies updates to the block
     * settings and/or related BlockContent records according to the incoming request
     * data and the specific block type configuration.
     *
     * @param int   $id       The identifier of the block to be updated.
     * @param int   $type_id  The identifier of the block type defining the block's structure and behavior.
     * @param mixed $request  The request object or data array containing the new block settings and content.
     *
     * @return void
     */
    public static function update_block($id, $type_id, $request)
    {
        $block = Block::find($id);
        if (!$block) return;

        $block_type = BlockType::find($type_id);
        if (!$block_type) return;

        // EDITOR
        if ($block_type->type == 'editor') {
            $block_settings = [
                'bg_color' => ($request->use_custom_bg ? $request->bg_color : null),
            ];
        }

        // Extra content HERO            
        if ($block_type->type == 'hero') {
            $block_settings = [
                'image_position' => $request->image_position,
                'cover_fixed' => null,
                'cover_dark' => null,
                'img_container_width' => $request->img_container_width,
                'img_col' => $request->img_col,
                'img_click' => null,
                'text_align' => $request->text_align ?? 'left',
                'padding_y' => $request->padding_y ?? null
            ];

            if ($request->use_image) $block_settings['use_image'] = $request->use_image;
            if ($request->shadow) $block_settings['shadow'] = $request->shadow;
            if ($request->shadow_title) $block_settings['shadow_title'] = $request->shadow_title;
            if ($request->shadow_content) $block_settings['shadow_content'] = $request->shadow_content;
            if ($request->cover_fixed) $block_settings['cover_fixed'] = $request->cover_fixed;
            if ($request->cover_dark) $block_settings['cover_dark'] = $request->cover_dark;
            if ($request->img_click) $block_settings['img_click'] = $request->img_click;

            if ($request->hasFile('image')) {
                $media = FileFunctions::store_file($block, $request->file('image'), 'block_media');
                if ($media) {
                    $block->update(['media_id' => $media->id]);
                    $media->update(['post_id' => $block->post_id ?? null]);
                } else
                    $block->update(['media_id' => $request->existing_image ?? null]);
            }
        }


        // Extra content SLIDER
        if ($block_type->type == 'slider') {
            $block_settings = [
                'bg_style' => $request->bg_style,
                'bg_color' => $request->bg_color ?? null,
                'slider_id' => $request->slider_id ?? null,
                'cover_fixed' => $request->cover_fixed ?? null,
                'cover_dark' => $request->cover_dark ?? null,
                'delay_seconds' => $request->delay_seconds ?? null,
                'shadow_title' => $request->shadow_title ?? null,
                'shadow_content' => $request->shadow_content ?? null,
                'button_id' => $request->button_id ?? null,
                'button_size' => $request->button_size ?? null,
                'font_color_title' => $request->font_color_title ?? null,
                'font_color_content' => $request->font_color_content ?? null,
                'font_size_title' => $request->font_size_title ?? null,
                'font_size_content' => $request->font_size_content ?? null,
                'rounded_images' => $request->rounded_images ?? null,
                'padding_y' => $request->padding_y ?? null
            ];

            $media = null;

            // delete image (if checkbox is checked)
            if ($request->has('delete_bg_image')) {
                FileFunctions::delete_file($block, 'block_media');
                $block->update(['media_id' => null]);
            }

            if ($request->hasFile('bg_image')) {
                $media = FileFunctions::store_file($block, $request->file('bg_image'), 'block_media');
                if ($media) {
                    $block->update(['media_id' => $media->id]);
                    $media->update(['post_id' => $block->post_id ?? null]);
                } else
                    $block->update(['media_id' => $request->existing_image ?? null]);
            }

            /*
            if ($request->hasFile('bg_image')) {
                $media = FileFunctions::store_image($request->file('bg_image'), $old_media_id = $request->existing_bg_media_id);
                if ($media) {
                    $block_settings['bg_media_id'] = $media->id;
                    $media->update(['post_id' => $block->post_id ?? null]);
                }
            }
                */
        }

        // Extra content ALERT            
        if ($block_type->type == 'alert') {
            $block_settings = ['type' => ($request->alert_type ? $request->alert_type : null)];
        }

        // Extra content LINKS            
        if ($block_type->type == 'links') {
            $block_settings = [
                'display_style' => ($request->display_style ? $request->display_style : null),
                'new_tab' => ($request->new_tab ? $request->new_tab : null)
            ];
        }

        // Extra content ACCORDION            
        if ($block_type->type == 'accordion') {
            $block_settings = [
                'remove_border' => ($request->remove_border ? $request->remove_border : null),
                'collapse_first_item' => ($request->collapse_first_item ? $request->collapse_first_item : null),
                'items_title_style_id' => ($request->use_custom_style_accordion_items_title ? $request->items_title_style_id : null),
                'items_content_style_id' => ($request->use_custom_style_accordion_items_content ? $request->items_content_style_id : null),
                'bg_color_item_active_title' => ($request->use_custom_bg_item_active_title ? $request->bg_color_item_active_title : null)
            ];
        }


        // Extra content TESTIMONIAL            
        if ($block_type->type == 'testimonial') {
            $block_settings = [
                'cols' => $request->cols ?? 4,
                'use_star_rating' => ($request->use_star_rating ? $request->use_star_rating : null),
                'use_images' => ($request->use_images ? $request->use_images : null),
                'items_style_id' => ($request->use_custom_style_items ? $request->items_style_id : null),
            ];
        }


        // Extra content VIDEO               
        if ($block_type->type == 'video') {
            $block_settings = ['full_width_responsive' => ($request->full_width_responsive ? $request->full_width_responsive : null)];
        }

        // Extra content IMAGE      
        if ($block_type->type == 'image') {
            $block_settings = [
                'shadow' => $request->shadow ?? null,
                'rounded' => $request->rounded ?? null,
            ];
        }

        // Extra content GALLERY        
        if ($block_type->type == 'gallery') {
            $block_settings = [
                'bg_color' => ($request->use_custom_bg ? $request->bg_color : null),
                'shadow' => $request->shadow ?? null,
                'rounded' => $request->rounded ?? null,
                'cols' => $request->cols ?? 4,
                'masonry_layout' => $request->masonry_layout ?? null,
                'masonry_cols' => $request->masonry_cols ?? 4,
                'masonry_gutter' =>  $request->masonry_gutter ?? 0
            ];
        }
        if ($request->cols) $block_settings['cols'] = $request->cols;
        $block_settings['icon_size'] = $request->icon_size ?? '2em';


        // Extra content CARD
        if ($block_type->type == 'card') {
            $block_settings = [
                'border_color' => null,
                'no_border_radius' => null,
                'bg_color_hover' => null,
                'same_height' => null,
                'horizontal' => null,
                'img_full_width' => null,
                'shadow' => null,
                'cols' => null
            ];

            if ($request->shadow) $block_settings['shadow'] = $request->shadow;
            if ($request->no_border_radius) $block_settings['no_border_radius'] = $request->no_border_radius;
            if ($request->same_height) $block_settings['same_height'] = $request->same_height;
            if ($request->horizontal) $block_settings['horizontal'] = $request->horizontal;
            if ($request->img_full_width) $block_settings['img_full_width'] = $request->img_full_width;
            if ($request->use_border) $block_settings['border_color'] = $request->border_color;
            if ($request->use_bg_color_hover) $block_settings['bg_color_hover'] = $request->bg_color_hover;
            if ($request->cols) $block_settings['cols'] = $request->cols ?? 4;
            if ($request->icon_size) $block_settings['icon_size'] = $request->icon_size ?? '2em';
            if ($request->link_location) $block_settings['link_location'] = $request->link_location;
            if ($request->link_btn_id) $block_settings['link_btn_id'] = $request->link_btn_id;
            if ($request->link_btn_size) $block_settings['link_btn_size'] = $request->link_btn_size;
            if ($request->link_btn_width) $block_settings['link_btn_width'] = $request->link_btn_width;
            if ($request->image_position) $block_settings['image_position'] = $request->image_position;
            if ($request->btn_id) $block_settings['btn_id'] = $request->btn_id;
        }

        // Extra content MAPS       
        if ($block_type->type == 'map') {
            $block_settings = ['height' => $request->height ?? 400, 'zoom' => $request->zoom ?? 16, 'address' => $request->address];
        }

        // Extra content BLOCKQUOTE       
        if ($block_type->type == 'blockquote') {
            $block_settings = ['shadow' => null, 'use_avatar' => null, 'avatar_media_id' => $request->existing_avatar_media_id];

            if ($request->use_avatar) {
                if ($request->hasFile('avatar_media_id')) {
                    $media = FileFunctions::store_file($block, $request->file('avatar_media_id'), 'block_media');
                    if ($media) {
                        $block->update(['media_id' => $media->id]);
                    } else
                        $block->update(['media_id' => $request->existing_avatar_media_id ?? null]);
                }
            }

            if ($request->shadow) $block_settings['shadow'] = $request->shadow;
            if ($request->use_avatar) $block_settings['use_avatar'] = $request->use_avatar;
        }

        // CUSTOM
        if ($block_type->type == 'custom') {
            $block_settings = [
                'bg_color' => ($request->use_custom_bg ? $request->bg_color : null),
            ];
        }

        // INCLUDE
        if ($block_type->type == 'include') {
            $block_settings = ['bg_color' => null];
            if ($request->use_custom_bg) $block_settings['bg_color'] = $request->bg_color;
        }

        // POST TABLE OF CONTENTS
        if ($block_type->type == 'post_toc') {
            $block_settings = [
                'bg_color' => ($request->use_custom_bg ? $request->bg_color : null),
                'block_align' => $request->block_align ?? null
            ];
        }

        // Extra content FORM               
        if ($block_type->type == 'form') {
            $block_settings = [
                'bg_color' => ($request->use_custom_bg ? $request->bg_color : null),
                'form_id' => $request->form_id ?? null,
                'button_id' => $request->button_id ?? null,
                'field_size' => $request->field_size ?? null
            ];
        }


        $block_settings['style_id'] = $request->use_custom_style ? $request->style_id : null;

        $block->update(['settings' => json_encode($block_settings ?? null, JSON_UNESCAPED_UNICODE)]);

        // ***************************************************
        // Block CONTENT
        // ***************************************************
        $langs = Language::get_languages();

        // UPDATE CONTENT
        foreach ($langs as $lang) {

            $block_content = BlockContent::FirstOrCreate(['block_id' => $id, 'lang_id' => $lang->id]);

            $data = null;

            $key_content = 'content_' . $lang->id;
            $key_add_header = 'add_header_' . $lang->id;
            $key_header_title = 'header_title_' . $lang->id;
            $key_header_content = 'header_content_' . $lang->id;
            $key_caption = 'caption_' . $lang->id;
            $key_title = 'title_' . $lang->id;
            $key_url = 'url_' . $lang->id;
            $key_existing_image = 'existing_image_' . $lang->id;
            $data = HelperFunctions::clean_text($request->$key_header_content);
            $header_array = array('add_header' => $request->$key_add_header, 'title' => $request->$key_header_title, 'content' => $data);
            $key_btn1_label = 'btn1_label_' . $lang->id;
            $key_btn1_url = 'btn1_url_' . $lang->id;
            $key_btn1_id = 'btn1_id_' . $lang->id;
            $key_btn1_icon = 'btn1_icon_' . $lang->id;
            $key_btn2_label = 'btn2_label_' . $lang->id;
            $key_btn2_url = 'btn2_url_' . $lang->id;
            $key_btn2_id = 'btn2_id_' . $lang->id;
            $key_btn2_icon = 'btn2_icon_' . $lang->id;

            // EXTRA HEADER CONTENT
            if ($block_type->type == 'form' || $block_type->type == 'gallery' || $block_type->type == 'card' || $block_type->type == 'editor' || $block_type->type == 'video' || $block_type->type == 'image' || $block_type->type == 'map' || $block_type->type == 'links' || $block_type->type == 'accordion') {
                $header_array = array('add_header' => $request->$key_add_header, 'title' => $request->$key_header_title, 'content' => $data = HelperFunctions::clean_text($request->$key_header_content));
                $header_content = json_encode($header_array, JSON_UNESCAPED_UNICODE);
                $block_content->update(['header' => $header_content]);
            }


            // EDITOR 
            if ($block_type->type == 'editor') {
                $data = $request->$key_content;
                if (!str_contains($data, '<pre ')) $data = HelperFunctions::clean_text($data);
                $data = json_encode(array('content' => $data), JSON_UNESCAPED_UNICODE);
            }

            // HERO
            if ($block_type->type == 'hero') {
                $data = array('title' => $request->$key_title, 'content' => $request->$key_content, 'btn1_label' => $request->$key_btn1_label, 'btn1_url' => $request->$key_btn1_url, 'btn1_id' => $request->$key_btn1_id, 'btn1_icon' => $request->$key_btn1_icon, 'btn2_label' => $request->$key_btn2_label, 'btn2_id' => $request->$key_btn2_id, 'btn2_url' => $request->$key_btn2_url, 'btn2_icon' => $request->$key_btn2_icon);
                $data = json_encode($data, JSON_UNESCAPED_UNICODE);
            }

            // CUSTOM
            if ($block_type->type == 'custom') {
                $data = $request->$key_content;
                $data = json_encode(array('content' => $data), JSON_UNESCAPED_UNICODE);
            }

            // VIDEO
            if ($block_type->type == 'video') {
                $data = array('embed' => $request->$key_embed, 'caption' => $request->$key_caption);
                $data = json_encode($data, JSON_UNESCAPED_UNICODE);
            }

            // IMAGE
            if ($block_type->type == 'image') {
                if ($request->hasFile('image_' . $lang->id)) {
                    $media = FileFunctions::store_file($block_content, $request->file('image_' . $lang->id), 'block_content_media');
                    if ($media) {
                        $block_content->update(['media_id' => $media->id]);
                        $media->update(['post_id' => $block->post_id ?? null]);
                    } else
                        $block_content->update(['media_id' => $request->$key_existing_image]);
                }
                $data = array('title' => $request->$key_title, 'caption' => $request->$key_caption, 'url' => $request->$key_url);
                $data = json_encode($data, JSON_UNESCAPED_UNICODE);
            }


            // ALERT
            if ($block_type->type == 'alert') {
                $post_key_title = 'title_' . $lang->id;
                $post_key_content = 'content_' . $lang->id;
                $data = array('title' => $request->$post_key_title, 'content' => HelperFunctions::clean_text($request->$post_key_content));
                $data = json_encode($data, JSON_UNESCAPED_UNICODE);
            }

            // POST SECTION
            if ($block_type->type == 'post_section') {
                $title_key = 'title_' . $lang->id;
                $slug_key = 'slug_' . $lang->id;

                if ($request->$slug_key) $slug = Str::slug($request->$slug_key, '-');
                else $slug = Str::slug($request->$title_key, '-');

                $data_array = array('title' => $request->$title_key, 'slug' => $slug);
                $data = json_encode($data_array, JSON_UNESCAPED_UNICODE);
            }

            // POST TABLE OF CONTENTS
            if ($block_type->type == 'post_toc') {
                $title_key = 'title_' . $lang->id;

                $data = array('title' => $request->$title_key);
                $data = json_encode($data, JSON_UNESCAPED_UNICODE);
            }

            // BLOCKQUOTE
            if ($block_type->type == 'blockquote') {
                $post_key_source = 'source_' . $lang->id;
                $post_key_content = 'content_' . $lang->id;
                $data_array = array('source' => $request->$post_key_source, 'content' => HelperFunctions::clean_text($request->$post_key_content));
                $data = json_encode($data_array, JSON_UNESCAPED_UNICODE);
            }

            // FORM
            if ($block_type->type == 'form') {
                $post_key_submit_text = 'button_submit_text_' . $lang->id;
                $data = array('button_submit_text' => $request->$post_key_submit_text);
                $data = json_encode($data, JSON_UNESCAPED_UNICODE);
            }

            // INCLUDE
            if ($block_type->type == 'include') {
                $key_tpl_file = 'tpl_file_' . $lang->id;

                $data = array('tpl_file' => $request->$key_tpl_file);
                $data = json_encode($data, JSON_UNESCAPED_UNICODE);
            }


            if (! ($block_type->type == 'gallery' || $block_type->type == 'slider' || $block_type->type == 'card'))
                $block_content->update(['data' => $data ?? null]);
        }
    }
}
