<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace Pivlu\Functions;

use Pivlu\Models\ConfigLang;
use Pivlu\Models\Post;
use Pivlu\Models\PostContent;
use Pivlu\Models\User;
use Pivlu\Models\PostType;
use Pivlu\Models\PostTypeContent;
use Pivlu\Models\PostTypeTaxonomy;
use Pivlu\Models\PostTypeTaxonomyContent;
use Pivlu\Models\Language;
use Pivlu\Models\Block;
use Pivlu\Models\BlockType;
use Pivlu\Models\BlockContent;
use Pivlu\Models\Theme;
use Pivlu\Models\ThemeButton;
use Pivlu\Models\ThemeFooter;
use Pivlu\Models\ThemeStyle;
use Pivlu\Models\ThemeMenu;
use Pivlu\Models\ThemeMenuItem;
use Pivlu\Models\ThemeMenuContent;
use Pivlu\Models\ThemeNav;
use Pivlu\Models\ThemeNavRow;
use Pivlu\Models\ThemeNavItem;
use Pivlu\Models\ThemeNavRowConfig;
use Pivlu\Models\Form;
use Pivlu\Models\FormDataStatus;
use Pivlu\Models\FormField;
use Pivlu\Models\FormFieldContent;
use Pivlu\Functions\HelperFunctions;
use Pivlu\Functions\ThemeFunctions;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class SetupFunctions
{

    // Add default post types, if not exists
    public static function check_default_post_types()
    {
        $default_language = Language::get_default_language();
        if (! $default_language) exit('Error. Default language not set.');

        if (PostType::where('type', 'page')->doesntExist()) {
            $post_type_page = PostType::create([
                'type' => 'page',
                'show_in_admin_menu' => 1,
                'admin_menu_icon' => '<i class="bi-files"></i>',
                'core' => 1,
                'active' => 1,
            ]);

            PostTypeContent::create([
                'lang_id' => $default_language->id,
                'post_type_id' => $post_type_page->id,
                'name' => 'Pages',
                'labels' => '{"singular":"Page","plural":"Pages","create":"Create new page","update":"Update page","delete":"Delete page","all":"All pages","search":"Search in pages"}',
            ]);
        }

        if (PostType::where('type', 'post')->doesntExist()) {
            $post_type_post = PostType::create([
                'type' => 'post',
                'show_in_admin_menu' => 1,
                'admin_menu_icon' => '<i class="bi-file-text"></i>',
                'core' => 1,
                'active' => 1,
                'allow_block_type' => 1,
            ]);

            PostTypeContent::create([
                'lang_id' => $default_language->id,
                'post_type_id' => $post_type_post->id,
                'name' => 'Posts',
                'slug' => 'posts',
                'labels' => '{"singular":"Post","plural":"Posts","create":"Create new post","update":"Update post","delete":"Delete post","all":"All posts","search":"Search in posts"}',
            ]);


            $post_type_taxonomy_categ = PostTypeTaxonomy::create([
                'hierarchical' => 1,
                'post_type_id' => $post_type_post->id,
                'active' => 1,
                'position' => 1,
                'admin_filter' => 1,
            ]);

            PostTypeTaxonomyContent::create([
                'lang_id' => $default_language->id,
                'post_type_taxonomy_id' => $post_type_taxonomy_categ->id,
                'name' => 'Categories',
                'slug' => 'category',
                'labels' => '{"singular":"Category","plural":"Categories","create":"Create category","update":"Update category","delete":"Delete category","all":"All categories","search":"Search category"}',
            ]);


            $post_type_taxonomy_tag = PostTypeTaxonomy::create([
                'hierarchical' => 0,
                'post_type_id' => $post_type_post->id,
                'active' => 1,
                'position' => 2,
                'admin_filter' => 1,
            ]);

            PostTypeTaxonomyContent::create([
                'lang_id' => $default_language->id,
                'post_type_taxonomy_id' => $post_type_taxonomy_tag->id,
                'name' => 'Tags',
                'slug' => 'tag',
                'labels' => '{"singular":"Tag","plural":"Tags","create":"Create tag","update":"Update tag","delete":"Delete tag","all":"All tags","search":"Search tag"}',
            ]);
        }
        return;
    }


    // Add a default language, if not exists        
    public static function check_default_language()
    {
        if (Language::where('is_default', 1)->doesntExist()) {
            Language::updateOrCreate(['code' => 'en'], [
                'is_default' => 1,
                'name' => 'English',
                'locale' => 'en_US',
                'status' => 'active',
                'timezone' => 'Europe/London',
                'dir' => 'ltr',
            ]);
        }
    }


    public static function check_default_website_settings()
    {
        // first admin user_id
        $first_admin_user = User::where('role_group', 'admin')->orderBy('id')->first();
        $admin_user_id = $first_admin_user->id;

        // id for page type
        $page_post_type = PostType::where(['type' => 'page'])->first();

        // Add contact page, if not exists
        $pivlu_contact_page_identificator = md5('pivlu_contact_page');
        if (Post::where(['identificator' => $pivlu_contact_page_identificator])->doesntExist()) {
            $contact_page_post = Post::create([
                'post_type_id' => $page_post_type->id,
                'identificator' => $pivlu_contact_page_identificator,
                'status' => 'published',
                'user_id' => $admin_user_id
            ]);

            PostContent::create([
                'lang_id' => Language::get_default_language()->id,
                'post_id' => $contact_page_post->id,
                'title' => 'Contact',
                'slug' => 'contact'
            ]);

            $contact_block_form = Block::create([
                'type_id' => BlockType::where('type', 'form')->value('id'),
                'post_id' => $contact_page_post->id,
                'source' => 'posts',
                'label' => 'Contact form',
                'position' => 1,
                'user_id' => $admin_user_id
            ]);

            $contact_form = Form::first();

            $block_settings = array('form_id' => $contact_form->id);
            $contact_block_form->update(['settings' => json_encode($block_settings, JSON_UNESCAPED_UNICODE)]);

            BlockFunctions::regenerate_post_blocks($contact_page_post->id);
        }


        ConfigLang::firstOrCreate(['lang_id' => Language::get_default_language()->id, 'name' => 'site_label'], ['value' => 'Pivlu Website']);
        ConfigLang::firstOrCreate(['lang_id' => Language::get_default_language()->id, 'name' => 'site_meta_title'], ['value' => 'Pivlu Website']);
        ConfigLang::firstOrCreate(['lang_id' => Language::get_default_language()->id, 'name' => 'site_meta_description'], ['value' => 'This website is created with Pivlu: Free CMS and Website Builder.']);
    }


    public static function check_form()
    {
        // add default dorms messages statuses (new and closed)
        FormDataStatus::firstOrCreate(
            ['is_new' => 1],
            ['label' => 'New', 'description' => 'This is the default status for new messages.', 'color' => '#14a151']
        );
        FormDataStatus::firstOrCreate(
            ['is_closed' => 1],
            ['label' => 'Closed', 'description' => 'This message is mark as closed. No future action is needed.', 'color' => '#1a1a1a']
        );



        // Add a contact form, if no form exists
        if (Form::doesntExist()) {
            $contact_form = Form::create([
                'label' => 'Contact form',
                'active' => 1,
            ]);

            // insert NAME field
            $field_name = FormField::create([
                'form_id' => $contact_form->id,
                'type' => 'text',
                'required' => 1,
                'col_md' => 6,
                'active' => 1,
                'position' => 0,
                'protected' => 1,
                'is_default_name' => 1
            ]);
            foreach (admin_languages() as $lang) {
                FormFieldContent::create(['form_id' => $contact_form->id, 'field_id' => $field_name->id, 'lang_id' => $lang->id, 'label' => 'Name']);
            }

            // insert EMAIL field
            $field_email = FormField::create([
                'form_id' => $contact_form->id,
                'type' => 'email',
                'required' => 1,
                'col_md' => 6,
                'active' => 1,
                'position' => 1,
                'protected' => 1,
                'is_default_email' => 1
            ]);
            foreach (admin_languages() as $lang) {
                FormFieldContent::create(['form_id' => $contact_form->id, 'field_id' => $field_email->id, 'lang_id' => $lang->id, 'label' => 'Email']);
            }

            // insert SUBJECT field
            $field_subject = FormField::create([
                'form_id' => $contact_form->id,
                'type' => 'text',
                'required' => 1,
                'col_md' => 12,
                'active' => 1,
                'position' => 2,
                'protected' => 1,
                'is_default_subject' => 1
            ]);
            foreach (admin_languages() as $lang) {
                FormFieldContent::create(['form_id' => $contact_form->id, 'field_id' => $field_subject->id, 'lang_id' => $lang->id, 'label' => 'Subject']);
            }

            // insert MESSAGE field
            $field_message = FormField::create([
                'form_id' => $contact_form->id,
                'type' => 'textarea',
                'required' => 1,
                'col_md' => 12,
                'active' => 1,
                'position' => 3,
                'protected' => 1,
                'is_default_message' => 1
            ]);
            foreach (admin_languages() as $lang) {
                FormFieldContent::create(['form_id' => $contact_form->id, 'field_id' => $field_message->id, 'lang_id' => $lang->id, 'label' => 'Message']);
            }
        }
    }

    public static function check_default_block_types()
    {
        BlockType::firstOrCreate(
            ['type' => 'editor'],
            [
                'core' => 1,
                'label' => 'Editor',
                'description' => 'Text editor',
                'core' => 1,
                'position' => 1,
                'icon' => '<i class="bi bi-textarea-t"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 1,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'image'],
            [
                'core' => 1,
                'label' => 'Image',
                'description' => 'Image / banner',
                'position' => 2,
                'icon' => '<i class="bi bi-image"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 1,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'gallery'],
            [
                'core' => 1,
                'label' => 'Images gallery',
                'description' => 'Images gallery',
                'position' => 3,
                'icon' => '<i class="bi bi-images"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 0,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'hero'],
            [
                'core' => 1,
                'label' => 'Hero',
                'description' => "A hero section is a prominent, visually striking area at the top of a webpage, designed to immediately capture a visitor's attention.",
                'position' => 4,
                'icon' => '<i class="bi bi-card-heading"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 0,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'card'],
            [
                'core' => 1,
                'label' => 'Card',
                'description' => 'A card is a flexible and extensible content container. It includes options for headers and footers, a wide variety of content, contextual background colors, and powerful display options.',
                'position' => 5,
                'icon' => '<i class="bi bi-file-richtext"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 0,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'slider'],
            [
                'core' => 1,
                'label' => 'Slider',
                'description' => 'A slider, also known as a carousel or slideshow, is a design element that displays a sequence of images, videos, text or other content, allowing users to navigate through them.',
                'position' => 6,
                'icon' => '<i class="bi bi-collection"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 0,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'video'],
            [
                'core' => 1,
                'label' => 'Video',
                'description' => 'A video block allows you to embed videos from various sources, enhancing your content with multimedia elements.',
                'position' => 7,
                'icon' => '<i class="bi bi-play-btn"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 0,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'map'],
            [
                'core' => 1,
                'label' => 'Map',
                'description' => 'Add a Google map.',
                'position' => 8,
                'icon' => '<i class="bi bi-geo-alt"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 0,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'alert'],
            [
                'core' => 1,
                'label' => 'Alert',
                'description' => 'Alert (info, warning, error, success)',
                'position' => 9,
                'icon' => '<i class="bi bi-exclamation-square"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 0,
                'allow_in_layout' => 1,
            ]
        );


        BlockType::firstOrCreate(
            ['type' => 'blockquote'],
            [
                'core' => 1,
                'label' => 'Blockquote',
                'description' => 'Blockquote',
                'position' => 10,
                'icon' => '<i class="bi bi-chat-left-quote"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 0,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'include'],
            [
                'core' => 1,
                'label' => 'Include file',
                'description' => 'Include file content',
                'position' => 11,
                'icon' => '<i class="bi bi-file-earmark-plus"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 1,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'custom'],
            [
                'core' => 1,
                'label' => 'Custom code',
                'description' => 'Custom code',
                'position' => 12,
                'icon' => '<i class="bi bi-code"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 1,
                'allow_in_layout' => 1,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'form'],
            [
                'core' => 1,
                'label' => 'Form',
                'description' => 'Form',
                'position' => 13,
                'icon' => '<i class="bi bi-textarea-resize"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 0,
                'allow_in_layout' => 0,
            ]
        );


        BlockType::firstOrCreate(
            ['type' => 'post_section'],
            [
                'core' => 1,
                'label' => 'Post Sction',
                'description' => 'Add a new section in this article',
                'position' => 14,
                'icon' => '<i class="bi bi-distribute-vertical"></i>',
                'allow_in_homepage' => 0,
                'allow_in_posts' => 1,
                'allow_in_footer' => 0,
                'allow_in_layout' => 0,
            ]
        );

        BlockType::firstOrCreate(
            ['type' => 'links'],
            [
                'core' => 1,
                'label' => 'Links',
                'description' => 'Add a links list',
                'position' => 15,
                'icon' => '<i class="bi bi-distribute-vertical"></i>',
                'allow_in_homepage' => 1,
                'allow_in_posts' => 1,
                'allow_in_footer' => 1,
                'allow_in_layout' => 1,
            ]
        );
    }


    // Add default theme, if not exists        
    public static function check_default_theme()
    {
        $theme = Theme::firstorCreate(
            ['is_active' => 1],
            [
                'code' => HelperFunctions::generateRandomInteger(16),
                'is_builder' => 1,
                'name' => 'Default theme',
                'description' => 'This is the default theme included with Pivlu CMS. This is a theme created with theme builder',
                'vendor_name' => 'pivlu',
                'package_name' => 'theme-default',
                'views_hint' => 'pivlu',
                'nav_id' => ThemeNav::where('is_default', 1)->value('id'),
                'footer_id' => ThemeFooter::where('is_default', 1)->value('id'),
            ]
        );
    }



    // Add a default button, if not exists        
    public static function check_default_button()
    {
        if (ThemeButton::where('is_default', 1)->doesntExist()) {
            $data = [
                'bg_color' => config('pivlu.defaults.button_bg_color'),
                'font_color' => config('pivlu.defaults.button_font_color'),
                'border_color' => config('pivlu.defaults.button_border_color'),
                'bg_color_hover' => config('pivlu.defaults.button_bg_color_hover'),
                'font_color_hover' => config('pivlu.defaults.button_font_color_hover'),
                'border_color_hover' => config('pivlu.defaults.button_border_color_hover'),
                'shadow' => null,
                'rounded' => null,
                "font_weight" => 'normal',
                "size" => null,
            ];

            ThemeButton::create([
                'is_default' => 1,
                'label' => 'Default button',
                'data' => json_encode($data)
            ]);
        }
    }


    // Add a default style, if not exists        
    public static function check_default_style()
    {
        if (ThemeStyle::where('is_default', 1)->doesntExist()) {
            $data = [
                "text_size" => "1rem",
                "text_color" => "black",
                "text_font_weight" => "normal",
                "text_align" => "left",
                "link_color" => "#2272dd",
                "link_hover_color" => "black",
                "link_underline_color" => "black",
                "link_underline_color_hover" => "black",
                "link_decoration" => "none",
                "link_hover_decoration" => "none",
                "link_font_weight" => "bold",
                "link_underline_thickness" => "auto",
                "link_underline_offset" => "auto",
                "title_size" => "1.4rem",
                "subtitle_size" => "1.2rem",
                "title_font_weight" => "normal",
                "subtitle_font_weight" => "normal",
                "caption_color" => "grey",
                "caption_size" => "0.95rem",
                "caption_style" => "normal",
                "bg_color" => "#f3f6f4"
            ];

            ThemeStyle::create([
                'is_default' => 1,
                'label' => 'Header navigation primary row',
                'data' => json_encode($data)
            ]);          
        }
    }


    public static function check_default_menu()
    {
        // Add default menu, if not exists
        if (ThemeMenu::where(['is_default' => 1])->doesntExist()) {
            $menu = ThemeMenu::create([
                'label' => 'Default menu',
                'is_default' => 1,
            ]);

            $menu_item = ThemeMenuItem::create([
                'menu_id' => $menu->id,
                'type' => 'home',
                'position' => 1
            ]);

            ThemeMenuContent::create([
                'lang_id' => Language::get_default_language()->id,
                'menu_id' => $menu->id,
                'item_id' => $menu_item->id,
                'label' => 'Home'
            ]);

            ThemeFunctions::generate_menu_links($menu->id);
        }
    }


    public static function check_default_nav()
    {
        // Add default navigation, if not exists
        if (ThemeNav::where(['is_default' => 1])->doesntExist()) {
            $nav = ThemeNav::create([
                'label' => 'Default navigation',
                'is_default' => 1,
            ]);

            $nav_row = ThemeNavRow::create([
                'nav_id' => $nav->id,
                'position' => 1,
                'active' => 1,
            ]);

            $nav_row_item1 = ThemeNavItem::create([
                'nav_id' => $nav->id,
                'row_id' => $nav_row->id,
                'column' => 'left',
                'type' => 'logo',
                'position' => 1,
                'active' => 1,
            ]);

            $nav_row_item2 = ThemeNavItem::create([
                'nav_id' => $nav->id,
                'row_id' => $nav_row->id,
                'column' => 'right',
                'type' => 'login_register',
                'position' => 2,
                'active' => 1,
            ]);

            $nav_row_item2 = ThemeNavItem::create([
                'nav_id' => $nav->id,
                'row_id' => $nav_row->id,
                'column' => 'right',
                'type' => 'menu_links',
                'position' => 1,
                'active' => 1,
                'menu_links_id' => ThemeMenu::where('is_default', 1)->value('id') ?? null,
            ]);

            $default_theme = Theme::where('is_active', 1)->first();
            if ($default_theme) {
                if (!$default_theme->nav_id) $default_theme->update(['nav_id' => $nav->id]);
            }

            ThemeNavRowConfig::updateOrCreate(
                ['nav_id' => $nav->id, 'row_id' => $nav_row->id, 'name' => 'style_id'],
                ['value' => ThemeStyle::where('is_default', 1)->value('id') ?? null]
            );
        }
    }


    public static function check_default_footer()
    {
        // Add default footer, if not exists
        $default_footer = ThemeFooter::firstorCreate(
            ['is_default' => 1],
            [
                'label' => 'Default footer',
                'footer_columns' => 1,
            ]
        );

        $editor_block_type = BlockType::where(['type' => 'editor'])->first();

        $footer_block = Block::firstorCreate(
            [
                'footer_id' => $default_footer->id,
                'type_id' => $editor_block_type->id,
            ],
            [
                'footer_destination' => 'primary',
                'footer_col' => 1,
                'position' => 1,
                'label' => 'Copyright'
            ]
        );

        $footer_content = array('content' => 'Powered by <a target="_blank" href="https://pivlu.com">Pivlu - Free CMS and Website Builder</a>');

        BlockContent::firstorCreate(
            [
                'lang_id' => Language::get_default_language()->id,
                'block_id' => $footer_block->id,
            ],
            [
                'data' => json_encode($footer_content, JSON_UNESCAPED_UNICODE)
            ]
        );
    }

    // Add default roles and permissions, if not exists
    public static function check_default_roles_and_permissions()
    {
        $post_types = PostType::all();

        // DEFAULT ROLES
        $role_admin = Role::updateOrCreate(['name' => 'admin'], [
            'label' => 'Administrator',
            'description' => 'Has complete control over the entire application, including access to all features, settings, and the ability to manage any account.',
            'role_group' => 'admin',
        ]);
        $role_manager = Role::updateOrCreate(['name' => 'manager'], [
            'label' => 'Manager',
            'description' => 'The manager has complete control over the content.',
            'role_group' => 'internal',
        ]);
        $role_posts_editor = Role::updateOrCreate(['name' => 'posts_editor'], [
            'label' => 'Content editor',
            'description' => 'The post editor can manage and publish all posts and pages, manage post types, moderate comments, but cannot access the app settings.',
            'role_group' => 'internal',
        ]);
        $role_posts_author = Role::updateOrCreate(['name' => 'posts_author'], [
            'label' => 'Content author',
            'description' => 'The post author has the ability to create, edit, and publish their own articles, but not those created by others.',
            'role_group' => 'internal',
        ]);
        $role_posts_contributor = Role::updateOrCreate(['name' => 'posts_contributor'], [
            'label' => 'Content contributor',
            'description' => 'Post contributors can create and edit their own articles, but must submit them for approval by an editor, manager, or administrator.',
            'role_group' => 'internal',
        ]);
        $role_registered = Role::updateOrCreate(['name' => 'registered'], [
            'label' => 'Registered user',
            'description' => 'User registering using the registration page.',
            'role_group' => 'registered',
        ]);

        // DEFAULT PERMISSIONS - POSTS TYPES            
        foreach ($post_types as $post_type) {
            $perm_index = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_index'],
                [
                    'description' => 'Access to this section.',
                ]
            );

            $perm_view = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_view'],
                [
                    'description' => 'Permission to view their own content.',
                ]
            );

            $perm_viewAny =  Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_viewAny'],
                [
                    'description' => 'Permissio to view any content, including those created by others.',
                ]
            );

            $perm_create = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_create'],
                [
                    'description' => 'Create articles.',
                ]
            );

            $perm_update = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_update'],
                [
                    'description' => 'Update their own content.',
                ]
            );

            $perm_updateAny = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_updateAny'],
                [
                    'description' => 'Update any content, including those created by others.',
                ]
            );

            $perm_delete = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_delete'],
                [
                    'description' => 'Delete their own content.',
                ]
            );

            $perm_deleteAny = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_deleteAny'],
                [
                    'description' => 'Delete any content, including those created by others.',
                    'attention' => 1,
                ]
            );

            $perm_publish = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_publish'],
                [
                    'description' => 'Publish their own articles.',
                ]
            );

            $perm_publishAny = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_publishAny'],
                [
                    'description' => 'Publish any articles, including those created by others.',
                ]
            );

            $perm_update_published = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_update_published'],
                [
                    'description' => 'Edit or unpublish own articles after they are published.',
                ]
            );

            $perm_updateAny_published = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_updateAny_published'],
                [
                    'description' => 'Edit or unpublish any articles from any author after they are published.',
                ]
            );

            $perm_create_taxonomies = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_create_taxonomies'],
                [
                    'description' => 'The user can create taxonomies (categories, tags...)',
                ]
            );

            $perm_update_taxonomies = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_update_taxonomies'],
                [
                    'description' => 'The user can update any taxononomy (categories, tags...).',
                    'attention' => 1,
                ]
            );

            $perm_delete_taxonomies = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_delete_taxonomies'],
                [
                    'description' => 'The user can delete any taxononomy (categories, tags...).',
                    'attention' => 1,
                ]
            );

            $perm_view_comments = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_view_comments'],
                [
                    'description' => 'View comments and reactions.',
                ]
            );

            $perm_update_comments = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_update_comments'],
                [
                    'description' => 'Edit comments and reactions.',
                    'attention' => 1,
                ]
            );

            $perm_delete_comments = Permission::firstOrCreate(
                ['post_type_id' => $post_type->id ?? null, 'name' => $post_type->type . '_delete_comments'],
                [
                    'description' => 'Delete comments and reactions.',
                    'attention' => 1,
                ]
            );


            $perm_index->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [
                            'switchCheck-' . $perm_view->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_viewAny->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_create->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_update->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_updateAny->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_delete->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_deleteAny->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_publish->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_publishAny->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_update_published->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_updateAny_published->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_create_taxonomies->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_update_taxonomies->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_delete_taxonomies->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_view_comments->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_update_comments->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_delete_comments->id ?? null  => 'disabled',
                        ],
                        'checked' => []
                    ]
                )
            ]);


            $perm_view->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_viewAny->id ?? null  => 'disabled',
                        ]
                    ]
                )
            ]);

            $perm_viewAny->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_view->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_create->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_update->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_updateAny->id ?? null  => 'disabled',
                        ]
                    ]
                )
            ]);

            $perm_updateAny->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_update->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_delete->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_deleteAny->id ?? null  => 'disabled',
                        ]
                    ]
                )
            ]);

            $perm_deleteAny->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_delete->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_publish->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_publishAny->id ?? null  => 'disabled',
                        ]
                    ]
                )
            ]);

            $perm_publishAny->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_publish->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_update_published->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_updateAny_published->id ?? null  => 'disabled',
                        ]
                    ]
                )
            ]);

            $perm_updateAny_published->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_update_published->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_create_taxonomies->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_update_taxonomies->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_delete_taxonomies->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_view_comments->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [
                            'switchCheck-' . $perm_update_comments->id ?? null  => 'disabled',
                            'switchCheck-' . $perm_delete_comments->id ?? null  => 'disabled',
                        ],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_update_comments->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_view_comments->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);

            $perm_delete_comments->update([
                'actions' => json_encode(
                    [
                        'unchecked' => [],
                        'checked' => [
                            'switchCheck-' . $perm_index->id ?? null  => 'enabled',
                            'switchCheck-' . $perm_view_comments->id ?? null  => 'enabled',
                        ]
                    ]
                )
            ]);
        }

        // DEFAULT PERMISSIONS - POST TYPES ACCESS
        Permission::firstOrCreate(
            ['name' => 'create_custom_post_type'],
            [
                'description' => 'Create custom post type.',
                'attention' => 1,
            ]
        );

        Permission::firstOrCreate(
            ['name' => 'update_custom_post_type'],
            [
                'description' => 'Update custom post type.',
                'attention' => 1,
            ]
        );

        Permission::firstOrCreate(
            ['name' => 'delete_custom_post_type'],
            [
                'description' => 'Delete custom post type.',
                'attention' => 1,
            ]
        );


        // DEFAULT PERMISSIONS - FORMS
        $perm_view_forms_messages = Permission::firstOrCreate(
            ['name' => 'view_forms_messages'],
            [
                'description' => 'View messages from forms',
            ]
        );

        $perm_delete_forms_messages = Permission::firstOrCreate(
            ['name' => 'delete_forms_messages'],
            [
                'description' => 'Delete forms messages.',
                'attention' => 1,
            ]
        );

        $perm_reply_forms_messages = Permission::firstOrCreate(
            ['name' => 'reply_forms_messages'],
            [
                'description' => 'Reply to forms messages.',
                'attention' => 1,
            ]
        );

        $perm_view_forms_messages->update([
            'actions' => json_encode(
                [
                    'unchecked' => [
                        'switchCheck-' . $perm_delete_forms_messages->id ?? null  => 'disabled',
                        'switchCheck-' . $perm_reply_forms_messages->id ?? null  => 'disabled',
                    ],
                    'checked' => []
                ]
            )
        ]);


        // DEFAULT PERMISSIONS - THEMES
        $perm_view_themes = Permission::firstOrCreate(
            ['name' => 'view_themes'],
            [
                'description' => 'View themes and theme builder components (menus, styles, buttons, custom code...)',
            ]
        );

        $perm_install_themes = Permission::firstOrCreate(
            ['name' => 'install_themes'],
            [
                'description' => 'Create or install new themes.',
            ]
        );

        $perm_update_themes = Permission::firstOrCreate(
            ['name' => 'update_themes'],
            [
                'description' => 'Modify themes and manage theme builder components (menus, styles, buttons, custom code...)',
                'attention' => 1,
            ]
        );

        $perm_delete_themes = Permission::firstOrCreate(
            ['name' => 'delete_themes'],
            [
                'description' => 'Delete themes.',
            ]
        );

        $perm_switch_themes = Permission::firstOrCreate(
            ['name' => 'switch_themes'],
            [
                'description' => 'Switch themes (activate themes).',
                'attention' => 1,
            ]
        );

        $perm_view_themes->update([
            'actions' => json_encode(
                [
                    'unchecked' => [
                        'switchCheck-' . $perm_install_themes->id ?? null  => 'disabled',
                        'switchCheck-' . $perm_update_themes->id ?? null  => 'disabled',
                        'switchCheck-' . $perm_delete_themes->id ?? null  => 'disabled',
                        'switchCheck-' . $perm_switch_themes->id ?? null  => 'disabled',
                    ],
                    'checked' => []
                ]
            )
        ]);


        // DEFAULT PERMISSIONS - ACCOUNTS
        $perm_view_users = Permission::firstOrCreate(
            ['name' => 'view_accounts'],
            ['description' => 'View all accounts.']
        );

        $perm_create_users = Permission::firstOrCreate(
            ['name' => 'create_account'],
            ['description' => 'Create accounts.']
        );

        $perm_update_users = Permission::firstOrCreate(
            ['name' => 'update_account'],
            ['description' => 'Update accounts details.', 'attention' => 1]
        );

        $perm_delete_users = Permission::firstOrCreate(
            ['name' => 'delete_account'],
            ['description' => 'Delete accounts.', 'attention' => 1]
        );

        $perm_view_users->update([
            'actions' => json_encode(
                [
                    'unchecked' => [
                        'switchCheck-' . $perm_create_users->id ?? null  => 'disabled',
                        'switchCheck-' . $perm_update_users->id ?? null  => 'disabled',
                        'switchCheck-' . $perm_delete_users->id ?? null  => 'disabled',
                    ],
                    'checked' => []
                ]
            )
        ]);

        // ADD DEFAULT PERMISSIONS TO ROLES
        $role_manager = Role::where('name', 'manager')->first();
        $role_posts_editor = Role::where('name', 'posts_editor')->first();
        $role_posts_author = Role::where('name', 'posts_author')->first();
        $role_posts_contributor = Role::where('name', 'posts_contributor')->first();
        $permissions = Permission::all();

        foreach ($post_types as $post_type) {
            // Manager permissions
            $manager_perms = [
                $post_type->type . '_index',
                $post_type->type . '_viewAny',
                $post_type->type . '_create',
                $post_type->type . '_updateAny',
                $post_type->type . '_deleteAny',
                $post_type->type . '_publishAny',
                $post_type->type . '_updateAny_published',
                $post_type->type . '_create_taxonomies',
                $post_type->type . '_update_taxonomies',
                $post_type->type . '_view_comments',
                $post_type->type . '_update_comments',
                $post_type->type . '_delete_comments',
                $post_type->type . '_create_custom_post_type',
                $post_type->type . '_update_custom_post_type',
                $post_type->type . '_delete_custom_post_type',
            ];
            foreach ($permissions as $permission) {
                if (in_array($permission->name, $manager_perms)) $permission->assignRole($role_manager->name);
            }

            // Editor permissions
            $editor_perms = [
                $post_type->type . '_index',
                $post_type->type . '_viewAny',
                $post_type->type . '_create',
                $post_type->type . '_updateAny',
                $post_type->type . '_deleteAny',
                $post_type->type . '_publishAny',
                $post_type->type . '_updateAny_published',
                $post_type->type . '_create_taxonomies',
                $post_type->type . '_update_taxonomies',
                $post_type->type . '_view_comments',
                $post_type->type . '_update_comments',
                $post_type->type . '_delete_comments',
                $post_type->type . '_create_custom_post_type',
                $post_type->type . '_update_custom_post_type',
                $post_type->type . '_delete_custom_post_type',
            ];
            foreach ($permissions as $permission) {
                if (in_array($permission->name, $editor_perms)) $permission->assignRole($role_posts_editor->name);
            }

            // Author permissions
            $author_perms = [
                $post_type->type . '_index',
                $post_type->type . '_view',
                $post_type->type . '_create',
                $post_type->type . '_update',
                $post_type->type . '_publish',
            ];
            foreach ($permissions as $permission) {
                if (in_array($permission->name, $author_perms)) $permission->assignRole($role_posts_author->name);
            }

            // Contributor permissions
            $contributor_perms = [
                $post_type->type . '_index',
                $post_type->type . '_view',
                $post_type->type . '_create',
                $post_type->type . '_update',
            ];
            foreach ($permissions as $permission) {
                if (in_array($permission->name, $contributor_perms)) $permission->assignRole($role_posts_contributor->name);
            }
        }
    }
}
