<?php

/**
 * Pivlu - Open source Business Platform.
 * Pivlu comes with a complete suite of tools that any business, team, or
 * website owner needs.
 *   https://pivlu.com
 *
 * Copyright (c) Iosif Gabriel Chimilevschi
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights.
 * When a modified version is used to provide a service over a network, the
 * complete source code of the modified version must be made available.
 *
 * @copyright    Copyright (c) Iosif Gabriel Chimilevschi
 * @license      https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author       Iosif Gabriel Chimilevschi <office@pivlu.com>
 *
 *  DO NOT edit this file manually. All changes will be lost after software
 *  update. For custom changes, use templates and plugins system.
 */

namespace App\Actions\Fortify;

use Illuminate\Contracts\Validation\Rule;
use Illuminate\Validation\Rules\Password;

trait PasswordValidationRules
{
    /**
     * Get the validation rules used to validate passwords.
     *
     * @return array<int, Rule|array<mixed>|string>
     */
    protected function passwordRules(): array
    {
        return ['required', 'string', Password::default(), 'confirmed'];
    }
}
