<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TaxonomyTerm extends Model
{

    protected $fillable = [
        'taxonomy',
        'hierarchical',
        'post_type',
        'name',    
        'active',
        'position',
        'admin_filter',
        'core',
        'count_posts'
    ];

    protected $table = 'pivlu_taxonomy_terms';

    public function content_post_type()
    {
        return $this->belongsTo(PostType::class, 'post_type', 'type');
    }

    public function taxonomies()
    {
        return $this->hasMany(Taxonomy::class, 'taxonomy', 'taxonomy');
    }

    public function active_taxonomies()
    {
        return $this->hasMany(Taxonomy::class, 'taxonomy', 'taxonomy')->where('active', 1);
    }

    public function root_taxonomies()
    {
        return $this->hasMany(Taxonomy::class, 'taxonomy', 'taxonomy')->whereNull('parent_id')->where('active', 1)->orderBy('position');
    }

    public static function get_hierarchical_taxonomies($post_type)
    {
        $items = TaxonomyTerm::with('root_taxonomies', 'content_post_type')            
            ->whereHas('taxonomies', function ($query) {
                $query->whereNull('parent_id')->where('active', 1);
            })
            ->where(['post_type' => $post_type, 'hierarchical' => 1, 'active' => 1])
            ->orderBy('position')
            ->get();
            
        return $items;
    }
}
