<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace Pivlu\Cms\Models;

use Illuminate\Database\Eloquent\Model;

class Block extends Model
{

    protected $fillable = [
        'type_id',
        'label',
        'settings',
        'post_id',
        'is_homepage_block',
        'theme_id',
        'position',
        'hidden',
        'user_id',
    ];

    protected $table = 'pivlu_blocks';


    public function block_type()
    {
        return $this->belongsTo(BlockType::class, 'type_id');
    }

    protected $appends = ['all_languages_contents'];

    /**
     * 
     * @return \Illuminate\Database\Eloquent\Relations\hasOne
     */
    public function content()
    {
        return $this->hasOne(BlockContent::class, 'block_id');
    }

    /**
     * 
     * @return \Illuminate\Database\Eloquent\Relations\hasOne
     */
    public function active_language_content()
    {
        return $this->hasOne(BlockContent::class, 'block_id')->where('lang_id', Language::get_active_language()->id);
    }

    public function default_language_content()
    {
        return $this->hasOne(BlockContent::class, 'block_id')->where('lang_id', Language::get_default_language()->id);
    }

    public function getAllLanguagesContentsAttribute()
    {
        $all_language_contents = [];
        $langs = Language::get_languages();
        foreach ($langs as $lang) {
            $content = BlockContent::where('lang_id', $lang->id)->where('block_id', $this->id)->first();
            $all_language_contents[] = ['lang_id' => $lang->id, 'lang_name' => $lang->name, 'lang_code' => $lang->code, 'content' => $content->content ?? null, 'header' => $content->header ?? null];
        }
        return json_decode(json_encode($all_language_contents));
    }
}
