<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace Pivlu\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class FormData extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'form_id',
        'status_id',
        'source_lang_id',
        'name',
        'email',
        'subject',
        'message',
        'ip',
        'geo',
        'referer',
        'read_at',
        'responded_at',
        'is_important',
        'is_spam',
        'status_changed_by_user_id',
    ];

    protected $table = 'pivlu_form_data';

    protected $appends = ['geo_data'];

    public function form(): BelongsTo
    {
        return $this->BelongsTo(Form::class, 'form_id');
    }

    public function status(): BelongsTo
    {
        return $this->BelongsTo(FormDataStatus::class, 'status_id');
    }

    public function statur_changes_by_user(): BelongsTo
    {
        return $this->BelongsTo(User::class, 'status_changed_by_user_id');
    }

    public function getGeoDataAttribute()
    {
        $geo = $this->geo;

        return json_decode($geo);
    }
}
