<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace Pivlu\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Casts\Attribute;

class PostTypeContent extends Model
{

    protected $fillable = [
        'post_type_id',
        'lang_id',
        'name',
        'labels',
        'slug',
        'title',
        'meta_title',
        'meta_description',
    ];

    protected $table = 'pivlu_post_type_content';

    public $timestamps = false;

    public function post_type()
    {
        return $this->belongsTo(PostType::class, 'post_type_id');
    }

    public function language()
    {
        return $this->belongsTo(Language::class, 'lang_id');
    }

    public function url(): Attribute
    {
        $post_type = PostType::find($this->post_type_id);
        $lang = Language::find($this->lang_id);

        if (!$post_type) return new Attribute(
            get: fn() => null
        );

        $type_slug = PostTypeContent::where(['post_type_id' => $this->post_type_id, 'lang_id' => $this->lang_id])->value('slug');
        
        if ($type_slug) {
            if ($lang->is_default == 0) {
                $return = route('locale.level1', ['lang' => $lang->code, 'slug' => $type_slug]) ?? null;
            } else
                $return = route('level1', ['slug' => $type_slug]) ?? null;
        } else {
            $return = null;
        }

        return new Attribute(
            get: fn() =>  $return
        );
    }
}
