<?php

/**
 * Pivlu - Open source CMS (Content Management System).
 * Pivlu comes with the complete suite of tools that any business, team, or website owner needs.
 * https://pivlu.com
 *
 * Copyright (c) Chimilevschi Iosif-Gabriel
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 
 * When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
 *    
 * @copyright   Copyright (c) Chimilevschi Iosif-Gabriel
 * @license     https://opensource.org/license/agpl-v3  AGPL-3.0 License.
 * @author      Chimilevschi Iosif-Gabriel <office@pivlu.com>
 * 
 *  DO NOT edit this file manually. All changes will be lost after software update. For custom changes, use templates ans plugins system.
 */

namespace Pivlu\Models;

use Illuminate\Database\Eloquent\Model;

class ThemeFooter extends Model
{
    protected $fillable = [
        'label',
        'is_default',
        'footer_columns',
        'footer2_show',
        'footer2_columns'
    ];

    protected $table = 'pivlu_theme_footers';

    //Get default footer
    public static function get_default_footer()
    {
        $menu = ThemeFooter::where('is_default', 1)->first();

        return $menu;
    }
}
